//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESSLOG
    {
        public int id { get; set; }
        public string Username { get; set; }
        public string Description { get; set; }
        public string RemoteIPAddress { get; set; }
        public string LocalIPAddress { get; set; }
        public string MACAddress { get; set; }
        public Nullable<System.DateTime> AccessDate { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
    }
}
