//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMISSION_REPORTED_CAPTURED_REMOVE
    {
        public string Institution_Code { get; set; }
        public string INDEX_NO { get; set; }
        public string UPI { get; set; }
        public string CAPTUREDBY { get; set; }
        public Nullable<System.DateTime> DateCaptured { get; set; }
    }
}
