//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMISSION_PROJECTIONS
    {
        public string UIC { get; set; }
        public string KNEC_CODE { get; set; }
        public string SPONSOR { get; set; }
        public Nullable<int> Boys_Border { get; set; }
        public Nullable<int> Boys_Day { get; set; }
        public Nullable<int> Boys { get; set; }
        public Nullable<int> Girls_Border { get; set; }
        public Nullable<int> Girls_Day { get; set; }
        public Nullable<int> Girls { get; set; }
        public Nullable<int> BoarderQuota { get; set; }
        public Nullable<int> DayQuota { get; set; }
        public Nullable<int> GTotal { get; set; }
        public string PrincipalMobile { get; set; }
        public string AlternateMobile { get; set; }
        public string Institution_Cluster { get; set; }
        public string Processed { get; set; }
        public Nullable<int> CurForm1Boys { get; set; }
        public Nullable<int> CurForm1Girls { get; set; }
        public Nullable<int> CurForm1T { get; set; }
    }
}
