//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMISSION_REQUESTSTEMP
    {
        public int RequestID { get; set; }
        public string School_Code { get; set; }
        public string Requestor { get; set; }
        public string INDEX_NO { get; set; }
        public string Student_Name { get; set; }
        public string Gender { get; set; }
        public string Admission { get; set; }
        public string RequestBy { get; set; }
        public string ParentIDNo { get; set; }
        public string ParentMobile { get; set; }
        public Nullable<System.DateTime> DateCaptured { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string Category { get; set; }
        public string TOT { get; set; }
        public string ProcessedBy { get; set; }
        public Nullable<System.DateTime> ProcessedOn { get; set; }
    }
}
