//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMISSION_REPORTING_TEMP
    {
        public int IDz { get; set; }
        public string Institution_Code { get; set; }
        public string INDEX_NO { get; set; }
        public string UPI { get; set; }
        public string BIRTHCERT { get; set; }
        public Nullable<System.DateTime> DATEREPORTED { get; set; }
        public string CAPTUREDBY { get; set; }
        public string Name { get; set; }
        public string InstitutionName { get; set; }
        public string Gender { get; set; }
        public string TOT { get; set; }
        public string Knec_Code { get; set; }
        public string SchoolSelected { get; set; }
        public string Processed { get; set; }
    }
}
