//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APILogin
    {
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string active { get; set; }
        public string Organization { get; set; }
    }
}
