//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public int AccountID { get; set; }
        public string Institution_Code { get; set; }
        public string Bank_code { get; set; }
        public string Branch_code { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string AccountType { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> DateAccountOpened { get; set; }
        public Nullable<System.DateTime> DateAccountClosed { get; set; }
        public string Done_By { get; set; }
        public Nullable<System.DateTime> Date_Done { get; set; }
    }
}
