//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPITATION_RECOVERY_DESCRIPTION
    {
        public System.DateTime RecoveryDate { get; set; }
        public string RecoveryDesc { get; set; }
        public Nullable<bool> Locked { get; set; }
    }
}
