//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPITATION_RECOVERIES_MAY2019
    {
        public Nullable<double> SNO { get; set; }
        public string County { get; set; }
        public string SubCounty { get; set; }
        public string school { get; set; }
        public Nullable<double> Excess_enrolment { get; set; }
        public Nullable<double> Expected_ { get; set; }
        public Nullable<double> Recover { get; set; }
        public decimal TotalRec { get; set; }
        public Nullable<double> BalanceRecover { get; set; }
        public Nullable<double> AmountRec { get; set; }
        public string UIC { get; set; }
        public int RecoveryID { get; set; }
        public Nullable<bool> WholeRecovery { get; set; }
        public string AccType { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
