//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPITATION_LEARNERS_LCOUNT
    {
        public string Transaction_Id { get; set; }
        public string Institution_Code { get; set; }
        public string Institution_Name { get; set; }
        public string County_Name { get; set; }
        public string Sub_County_Name { get; set; }
        public Nullable<int> Learners { get; set; }
        public Nullable<int> LearnersOld { get; set; }
        public Nullable<int> Variance { get; set; }
    }
}
