//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPITATION_RECOVERY_WHOLEAMOUNT
    {
        public int TransactionID { get; set; }
        public string UIC { get; set; }
        public string Institution_Name { get; set; }
        public Nullable<int> Enrol { get; set; }
        public Nullable<decimal> GlobalAmount { get; set; }
        public Nullable<decimal> TotalAmountRec { get; set; }
        public Nullable<decimal> BalanceAfterRecovery { get; set; }
    }
}
