//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPITATION_LEARNERS_LOWCOUNT2
    {
        public Nullable<int> TransationID { get; set; }
        public string Institution_Code { get; set; }
        public Nullable<int> Learners { get; set; }
        public Nullable<int> LearnersWithoutF1 { get; set; }
        public Nullable<int> LearnersF1 { get; set; }
    }
}
