//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPITATION_RECOVERY_AMOUNT_SEPTEMBER_AUDITREC2
    {
        public string TransID { get; set; }
        public string UIC { get; set; }
        public string RecRate { get; set; }
        public int RecoveryID { get; set; }
        public Nullable<double> PendingRecovery { get; set; }
        public string AccType { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<double> BalanceAfter { get; set; }
        public Nullable<double> RecoveryAmount { get; set; }
    }
}
