//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPITATION_FINAL_DISBURSEMENT_TRANSITION_SEPT_DETAILED2
    {
        public string UIC { get; set; }
        public string Institution_Name { get; set; }
        public Nullable<int> Enrol { get; set; }
        public string AccType { get; set; }
        public string Bank_Name { get; set; }
        public string Sort_Code { get; set; }
        public string Branch_Name { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> JanRateAmount { get; set; }
        public Nullable<decimal> PlannedJanAmount { get; set; }
        public decimal RecoveryJanAmount { get; set; }
        public decimal PaidJanAmount { get; set; }
        public Nullable<decimal> VarianceJan { get; set; }
        public Nullable<decimal> MayRateAmount { get; set; }
        public Nullable<decimal> PlannedMayAmount { get; set; }
        public decimal RecoveryMayAmount { get; set; }
        public decimal PaidMayAmount { get; set; }
        public Nullable<decimal> VarianceMay { get; set; }
        public Nullable<decimal> JulyRateAmount { get; set; }
        public Nullable<decimal> PlannedJulyAmount { get; set; }
        public decimal RecoveryJulyAmount { get; set; }
        public decimal PaidJulyAmount { get; set; }
        public Nullable<decimal> VarianceJuly { get; set; }
        public Nullable<decimal> SeptRateAmount { get; set; }
        public Nullable<decimal> PlannedSeptAmount { get; set; }
        public decimal AuditReimbursement { get; set; }
        public decimal RecoverySeptAmount2 { get; set; }
        public decimal PaidSeptAmount { get; set; }
        public Nullable<decimal> OverallVariance { get; set; }
        public Nullable<decimal> EffectiveSeptAmount { get; set; }
        public Nullable<decimal> RecoverySeptAmount { get; set; }
        public Nullable<decimal> FinalSeptAmount { get; set; }
    }
}
