//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPITATION_RECOVERIES_AUG2019
    {
        public string TransID { get; set; }
        public string UIC { get; set; }
        public string RecoveryRate { get; set; }
        public int RecoveryID { get; set; }
        public Nullable<double> Amount { get; set; }
        public string AccType { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
