//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPITATION
    {
        public int Transaction_id { get; set; }
        public Nullable<int> Caputation_Amount { get; set; }
        public string Done_By { get; set; }
        public Nullable<System.DateTime> Date_Captured { get; set; }
        public Nullable<bool> Closed { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<System.DateTime> ClosedOn { get; set; }
        public string Description { get; set; }
        public string Level_Code { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> CurrentActive { get; set; }
        public Nullable<decimal> RecoveryRate { get; set; }
        public Nullable<bool> Hidden { get; set; }
    }
}
