//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPITATION_FINAL_ENROLMENT
    {
        public int TransactionID { get; set; }
        public string UIC { get; set; }
        public string Category { get; set; }
        public string AccType { get; set; }
        public int FromTransactionID { get; set; }
        public Nullable<int> Enrol { get; set; }
    }
}
