//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBCEvaluationMatrix
    {
        public string CenterID { get; set; }
        public int AssessorID { get; set; }
        public Nullable<int> Q1 { get; set; }
        public Nullable<int> Q2 { get; set; }
        public Nullable<int> Q3 { get; set; }
        public Nullable<int> Q4 { get; set; }
        public Nullable<int> Q5 { get; set; }
        public Nullable<int> Q6 { get; set; }
        public Nullable<int> Q7 { get; set; }
        public Nullable<int> Q8 { get; set; }
        public Nullable<int> Q9 { get; set; }
        public Nullable<int> Q10 { get; set; }
        public Nullable<int> Q11 { get; set; }
        public Nullable<int> Q13 { get; set; }
        public Nullable<int> Q12 { get; set; }
        public Nullable<int> Q14 { get; set; }
        public Nullable<int> Q15 { get; set; }
        public Nullable<int> Q16 { get; set; }
        public Nullable<int> Q17 { get; set; }
        public Nullable<int> Q18 { get; set; }
        public Nullable<int> Q19 { get; set; }
        public Nullable<int> Q20 { get; set; }
        public string B1 { get; set; }
        public string B2 { get; set; }
        public string B3 { get; set; }
        public string QDesc1 { get; set; }
        public string QDesc2 { get; set; }
        public string QDesc3 { get; set; }
        public string QDesc4 { get; set; }
        public string QDesc5 { get; set; }
        public string QDesc6 { get; set; }
        public string QDesc7 { get; set; }
        public string QDesc8 { get; set; }
        public string QDesc9 { get; set; }
        public string QDesc10 { get; set; }
        public string QDesc11 { get; set; }
        public string QDesc12 { get; set; }
        public string QDesc13 { get; set; }
        public string QDesc14 { get; set; }
        public string QDesc15 { get; set; }
        public string QDesc16 { get; set; }
        public string QDesc17 { get; set; }
        public string QDesc18 { get; set; }
        public string QDesc19 { get; set; }
        public string QDesc20 { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
