//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSTITUENCY
    {
        public string Constituency_Code { get; set; }
        public string Constituency_Name { get; set; }
        public string County_Code { get; set; }
        public int Aid { get; set; }
    }
}
