//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATASHEET_DLP_POWER
    {
        public string UIC { get; set; }
        public string RegCertNo { get; set; }
        public Nullable<int> Electricity { get; set; }
        public string FailedSource { get; set; }
        public string LackTransformer { get; set; }
        public string AwaitingCommission { get; set; }
        public string AwaitingInspection { get; set; }
        public string WorkInProgress { get; set; }
        public string PendingMeter { get; set; }
        public string DisconnectedOnBill { get; set; }
        public string SchoolMeter { get; set; }
        public string DLPSchool { get; set; }
        public Nullable<int> DLPTabletsNo { get; set; }
        public string DLPIIPhase1 { get; set; }
    }
}
