//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATASHEET
    {
        public int DataID { get; set; }
        public string Year { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Closed { get; set; }
    }
}
