//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATASHEET_DESKS_SHORTAGE
    {
        public int DataID { get; set; }
        public string UIC { get; set; }
        public string Class_Code { get; set; }
        public Nullable<int> F { get; set; }
        public Nullable<int> M { get; set; }
        public Nullable<int> Desks { get; set; }
    }
}
