//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATASHEET_SINGLEPIECE
    {
        public int DataID { get; set; }
        public string UIC { get; set; }
        public string IsASAL { get; set; }
        public Nullable<int> MBoarders { get; set; }
        public Nullable<int> FBoarders { get; set; }
        public Nullable<int> MRegCand { get; set; }
        public Nullable<int> FRegCand { get; set; }
        public string MMeanScoreGrade { get; set; }
        public Nullable<decimal> MMeanScorePoints { get; set; }
        public string FMeanScoreGrade { get; set; }
        public Nullable<decimal> FMeanScorePoints { get; set; }
        public string SchoolMeanScoreGrade { get; set; }
        public Nullable<decimal> SchoolMeanScorePoints { get; set; }
        public Nullable<int> FCandsCPlusandAbove { get; set; }
        public Nullable<int> MCandsCPlusandAbove { get; set; }
        public Nullable<int> FCandsAdmittedF1 { get; set; }
        public Nullable<int> MCandsAdmittedF1 { get; set; }
        public Nullable<decimal> GoKFunding { get; set; }
        public Nullable<decimal> PTAFunding { get; set; }
        public Nullable<decimal> OtherFunding { get; set; }
        public Nullable<int> Electricity { get; set; }
        public string ElectricityOtherDesc { get; set; }
        public Nullable<int> WaterSource { get; set; }
        public string WaterSourceDesc { get; set; }
        public string HaveComputers { get; set; }
        public Nullable<int> NoComputers { get; set; }
        public Nullable<int> MTeachersTrainedOnICT { get; set; }
        public Nullable<int> FTeachersTrainedOnICT { get; set; }
        public string HaveTeacherHouses { get; set; }
        public Nullable<int> TeacherHouses { get; set; }
        public Nullable<int> FNonTeachingStaff { get; set; }
        public Nullable<int> MNonTeachingStaff { get; set; }
        public Nullable<int> FToilets { get; set; }
        public Nullable<int> MToilets { get; set; }
        public Nullable<int> FTeacherToilets { get; set; }
        public Nullable<int> MTeacherToilets { get; set; }
        public Nullable<int> Classrooms { get; set; }
        public Nullable<int> PermanentClassrooms { get; set; }
        public Nullable<int> TemporaryClassrooms { get; set; }
        public Nullable<int> PermanentClassesNotUsed { get; set; }
        public Nullable<int> ClassesWithoutClassrooms { get; set; }
        public Nullable<int> FSchoolFeeding { get; set; }
        public Nullable<int> MSchoolFeeding { get; set; }
        public Nullable<int> FDewormed { get; set; }
        public Nullable<int> MDewormed { get; set; }
        public string ScienceLab { get; set; }
        public Nullable<int> ScienceLabCount { get; set; }
        public string SchoolLibrary { get; set; }
        public string ECDEExist { get; set; }
        public Nullable<int> ECDEClassrooms { get; set; }
        public Nullable<decimal> ECDEResources { get; set; }
        public Nullable<bool> ECDEFeeding { get; set; }
    }
}
