//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPEClearedList
    {
        public string County { get; set; }
        public string SubCounty { get; set; }
        public string UIC { get; set; }
        public string Institution_Name { get; set; }
        public string TSC_Code { get; set; }
        public string KNEC_Code { get; set; }
        public string Enrolment { get; set; }
    }
}
