//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUND_AGENCY_PROGRAMME_PAYMENTMODE
    {
        public string PaymentModeId { get; set; }
        public string PaymentModeDesc { get; set; }
    }
}
