//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNDING_SOURCE
    {
        public string Source_Code { get; set; }
        public string Source_Name { get; set; }
        public Nullable<bool> Visible { get; set; }
    }
}
