//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUTION_DHIS_LIST
    {
        public int InstitutionID { get; set; }
        public string NEMISCode { get; set; }
        public string DHISCode { get; set; }
        public string Institution_Name { get; set; }
        public string Institution_Type { get; set; }
        public string Institution_Level { get; set; }
        public string Sub_County_Code { get; set; }
        public string Sub_County_Name { get; set; }
        public string County_Code { get; set; }
        public string County_Name { get; set; }
        public string Constituency_Code { get; set; }
        public string Constituency_Name { get; set; }
        public string HeadsName { get; set; }
        public string HeadsPhone { get; set; }
    }
}
