//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUTION_DHIS_TREATMENTDATA
    {
        public string Year { get; set; }
        public string DrugID { get; set; }
        public string InstitutionID { get; set; }
        public Nullable<int> TreatedPreSchoolM { get; set; }
        public Nullable<int> TreatedPreSchoolF { get; set; }
        public Nullable<int> TreatedPreSchoolT { get; set; }
        public Nullable<int> TreatedPriSchool6to14M { get; set; }
        public Nullable<int> TreatedPriSchool6to14F { get; set; }
        public Nullable<int> TreatedPriSchool6to14T { get; set; }
        public Nullable<int> TreatedPriSchool15to18M { get; set; }
        public Nullable<int> TreatedPriSchool15to18F { get; set; }
        public Nullable<int> TreatedPriSchool15to18T { get; set; }
        public Nullable<int> TreatedPriSchoolGT { get; set; }
        public Nullable<int> OutofSchool2to5YrM { get; set; }
        public Nullable<int> OutofSchool2to5YrF { get; set; }
        public Nullable<int> OutofSchool2to5YrT { get; set; }
        public Nullable<int> OutofSchool6to14YrM { get; set; }
        public Nullable<int> OutofSchool6to14YrF { get; set; }
        public Nullable<int> OutofSchool6to14YrT { get; set; }
        public Nullable<int> OutofSchool15to18YrM { get; set; }
        public Nullable<int> OutofSchool15to18YrF { get; set; }
        public Nullable<int> OutofSchool15to18YrT { get; set; }
        public Nullable<int> TreatedAdults { get; set; }
        public Nullable<int> TreatedPriSchool6to14M1 { get; set; }
        public Nullable<int> TreatedPriSchool6to14F1 { get; set; }
        public Nullable<int> TreatedPriSchool6to14T1 { get; set; }
        public Nullable<int> TreatedPriSchool15to18M1 { get; set; }
        public Nullable<int> TreatedPriSchool15to18F1 { get; set; }
        public Nullable<int> TreatedPriSchool15to18T1 { get; set; }
        public Nullable<int> TreatedPriSchoolGT1 { get; set; }
        public Nullable<int> TreatedPriSchool6to14M2 { get; set; }
        public Nullable<int> TreatedPriSchool6to14F2 { get; set; }
        public Nullable<int> TreatedPriSchool6to14T2 { get; set; }
        public Nullable<int> TreatedPriSchool15to18M2 { get; set; }
        public Nullable<int> TreatedPriSchool15to18F2 { get; set; }
        public Nullable<int> TreatedPriSchool15to18T2 { get; set; }
        public Nullable<int> TreatedPriSchoolGT2 { get; set; }
        public Nullable<int> TreatedPriSchool6to14M3 { get; set; }
        public Nullable<int> TreatedPriSchool6to14F3 { get; set; }
        public Nullable<int> TreatedPriSchool6to14T3 { get; set; }
        public Nullable<int> TreatedPriSchool15to18M3 { get; set; }
        public Nullable<int> TreatedPriSchool15to18F3 { get; set; }
        public Nullable<int> TreatedPriSchool15to18T3 { get; set; }
        public Nullable<int> TreatedPriSchoolGT3 { get; set; }
        public Nullable<int> TreatedPriSchool6to14M4 { get; set; }
        public Nullable<int> TreatedPriSchool6to14F4 { get; set; }
        public Nullable<int> TreatedPriSchool6to14T4 { get; set; }
        public Nullable<int> TreatedPriSchool15to18M4 { get; set; }
        public Nullable<int> TreatedPriSchool15to18F4 { get; set; }
        public Nullable<int> TreatedPriSchool15to18T4 { get; set; }
        public Nullable<int> TreatedPriSchoolGT4 { get; set; }
        public Nullable<int> TreatedPriSchool6to14M5 { get; set; }
        public Nullable<int> TreatedPriSchool6to14F5 { get; set; }
        public Nullable<int> TreatedPriSchool6to14T5 { get; set; }
        public Nullable<int> TreatedPriSchool15to18M5 { get; set; }
        public Nullable<int> TreatedPriSchool15to18F5 { get; set; }
        public Nullable<int> TreatedPriSchool15to18T5 { get; set; }
        public Nullable<int> TreatedPriSchoolGT5 { get; set; }
        public Nullable<int> TreatedPriSchool6to14M6 { get; set; }
        public Nullable<int> TreatedPriSchool6to14F6 { get; set; }
        public Nullable<int> TreatedPriSchool6to14T6 { get; set; }
        public Nullable<int> TreatedPriSchool15to18M6 { get; set; }
        public Nullable<int> TreatedPriSchool15to18F6 { get; set; }
        public Nullable<int> TreatedPriSchool15to18T6 { get; set; }
        public Nullable<int> TreatedPriSchoolGT6 { get; set; }
        public Nullable<int> TreatedPriSchool6to14M7 { get; set; }
        public Nullable<int> TreatedPriSchool6to14F7 { get; set; }
        public Nullable<int> TreatedPriSchool6to14T7 { get; set; }
        public Nullable<int> TreatedPriSchool15to18M7 { get; set; }
        public Nullable<int> TreatedPriSchool15to18F7 { get; set; }
        public Nullable<int> TreatedPriSchool15to18T7 { get; set; }
        public Nullable<int> TreatedPriSchoolGT7 { get; set; }
        public Nullable<int> TreatedPriSchool6to14M8 { get; set; }
        public Nullable<int> TreatedPriSchool6to14F8 { get; set; }
        public Nullable<int> TreatedPriSchool6to14T8 { get; set; }
        public Nullable<int> TreatedPriSchool15to18M8 { get; set; }
        public Nullable<int> TreatedPriSchool15to18F8 { get; set; }
        public Nullable<int> TreatedPriSchool15to18T8 { get; set; }
        public Nullable<int> TreatedPriSchoolGT8 { get; set; }
        public Nullable<int> TreatedOutSchool2to5M { get; set; }
        public Nullable<int> TreatedOutSchool2to5F { get; set; }
        public Nullable<int> TreatedOutSchool2to5T { get; set; }
        public Nullable<int> TreatedOutSchool6to14M { get; set; }
        public Nullable<int> TreatedOutSchool6to14F { get; set; }
        public Nullable<int> TreatedOutSchool6to14T { get; set; }
        public Nullable<int> TreatedOutSchool15to18M { get; set; }
        public Nullable<int> TreatedOutSchool15to18F { get; set; }
        public Nullable<int> TreatedOutSchool15to18T { get; set; }
        public Nullable<int> TabletsSpoiled { get; set; }
        public Nullable<int> TabletsRecieved { get; set; }
        public Nullable<int> TabletsTopped { get; set; }
        public Nullable<int> TabletsReturned { get; set; }
    }
}
