//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUTION_GEOADDRESS
    {
        public string UIC { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Pluscode { get; set; }
        public string Address { get; set; }
        public string LociLatitude { get; set; }
        public string LociLongitude { get; set; }
        public string LociPluscode { get; set; }
        public string LociAddress { get; set; }
        public string CTrans { get; set; }
    }
}
