//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUTION_LEARNERS_SUMMARIES
    {
        public string Institution_Code { get; set; }
        public string Class_Code { get; set; }
        public Nullable<int> BC_Boys { get; set; }
        public Nullable<int> BC_Girls { get; set; }
        public Nullable<int> BC_Unk { get; set; }
        public Nullable<int> BC_Total { get; set; }
        public Nullable<int> WBC_Boys { get; set; }
        public Nullable<int> WBC_Girls { get; set; }
        public Nullable<int> WBC_Unk { get; set; }
        public Nullable<int> WBC_Total { get; set; }
        public Nullable<int> Boys { get; set; }
        public Nullable<int> Girls { get; set; }
        public Nullable<int> Unk { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> NER_Boys { get; set; }
        public Nullable<int> NER_Girls { get; set; }
        public Nullable<int> NER_Unk { get; set; }
        public Nullable<int> NER_Total { get; set; }
    }
}
