//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUTION_SUMMARIES
    {
        public string Institution_Code { get; set; }
        public Nullable<int> BC_Boys { get; set; }
        public Nullable<int> BC_Girls { get; set; }
        public Nullable<int> BC_Unk { get; set; }
        public Nullable<int> BC_Total { get; set; }
        public Nullable<int> WBC_Boys { get; set; }
        public Nullable<int> WBC_Girls { get; set; }
        public Nullable<int> WBC_Unk { get; set; }
        public Nullable<int> WBC_Total { get; set; }
        public Nullable<int> TSC_Male { get; set; }
        public Nullable<int> TSC_Female { get; set; }
        public Nullable<int> TSC_Unk { get; set; }
        public Nullable<int> TSC_Total { get; set; }
        public Nullable<int> BOM_Male { get; set; }
        public Nullable<int> BOM_Female { get; set; }
        public Nullable<int> BOM_Unk { get; set; }
        public Nullable<int> BOM_Total { get; set; }
        public Nullable<int> Support_Male { get; set; }
        public Nullable<int> Support_Female { get; set; }
        public Nullable<int> Support_Unk { get; set; }
        public Nullable<int> Support_Total { get; set; }
    }
}
