//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUTION_REPORTED_CLASS_REP
    {
        public int TrackID { get; set; }
        public string UIC { get; set; }
        public string Class_Code { get; set; }
        public Nullable<int> Boys { get; set; }
        public Nullable<int> Girls { get; set; }
        public Nullable<int> Enrolment { get; set; }
        public Nullable<int> Reported { get; set; }
        public Nullable<int> RepBoys { get; set; }
        public Nullable<int> RepGirls { get; set; }
    }
}
