//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUTION_INFRASTRUCTURE_PROGRESS_STATUS
    {
        public string TypeID { get; set; }
        public int StatusID { get; set; }
        public string StatusDescription { get; set; }
        public string StatusDescriptionShort { get; set; }
        public Nullable<decimal> PercentRank { get; set; }
    }
}
