//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUTION_REPORTED_FAILED_REASONS
    {
        public int ReportedID { get; set; }
        public int TypeID { get; set; }
        public Nullable<int> Boys { get; set; }
        public Nullable<int> Girls { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
