//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUTION_DHIS_DATA
    {
        public string Year { get; set; }
        public string InstitutionID { get; set; }
        public Nullable<int> RegisterMPre { get; set; }
        public Nullable<int> RegisterFPre { get; set; }
        public Nullable<int> RegisterTPre { get; set; }
        public Nullable<int> RegisterM1 { get; set; }
        public Nullable<int> RegisterF1 { get; set; }
        public Nullable<int> RegisterT1 { get; set; }
        public Nullable<int> RegisterM2 { get; set; }
        public Nullable<int> RegisterF2 { get; set; }
        public Nullable<int> RegisterT2 { get; set; }
        public Nullable<int> RegisterM3 { get; set; }
        public Nullable<int> RegisterF3 { get; set; }
        public Nullable<int> RegisterT3 { get; set; }
        public Nullable<int> RegisterM4 { get; set; }
        public Nullable<int> RegisterF4 { get; set; }
        public Nullable<int> RegisterT4 { get; set; }
        public Nullable<int> RegisterM5 { get; set; }
        public Nullable<int> RegisterF5 { get; set; }
        public Nullable<int> RegisterT5 { get; set; }
        public Nullable<int> RegisterM6 { get; set; }
        public Nullable<int> RegisterF6 { get; set; }
        public Nullable<int> RegisterT6 { get; set; }
        public Nullable<int> RegisterM7 { get; set; }
        public Nullable<int> RegisterF7 { get; set; }
        public Nullable<int> RegisterT7 { get; set; }
        public Nullable<int> RegisterM8 { get; set; }
        public Nullable<int> RegisterF8 { get; set; }
        public Nullable<int> RegisterT8 { get; set; }
        public Nullable<int> RegisterM { get; set; }
        public Nullable<int> RegisterF { get; set; }
        public Nullable<int> RegisterT { get; set; }
    }
}
