//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUTION
    {
        public string Institution_Code { get; set; }
        public string Institution_Name { get; set; }
        public string Institution_Status { get; set; }
        public string Institution_Type { get; set; }
        public string Institution_Level_Code { get; set; }
        public string Sub_County_Code { get; set; }
        public string Institution_Current_Code { get; set; }
        public string Institution_Category_Code { get; set; }
        public string Institution_Cluster { get; set; }
        public string Classification_by_Gender { get; set; }
        public string Accommodation_Code { get; set; }
        public string Mobile_Institution { get; set; }
        public string Formal_Status { get; set; }
        public string Institution_Residence { get; set; }
        public string Constituency_Code { get; set; }
        public string Zone_Code { get; set; }
        public string Ward_Code { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Postal_Address { get; set; }
        public string Tel_Number { get; set; }
        public string Tel_Number2 { get; set; }
        public string Email_Address { get; set; }
        public string Mobile_Number1 { get; set; }
        public string Mobile_Number2 { get; set; }
        public string Website { get; set; }
        public string Premise_Ownership { get; set; }
        public string Ownership_Document { get; set; }
        public string Social_Media { get; set; }
        public string Education_System_Code { get; set; }
        public Nullable<System.DateTime> Registration_Date1 { get; set; }
        public string Proprietor_Code { get; set; }
        public string Registration_Certificate { get; set; }
        public string Nearest_Police_Station { get; set; }
        public string Nearest_Health_Facility { get; set; }
        public string Nearest_Town { get; set; }
        public string Captured_By { get; set; }
        public Nullable<System.DateTime> Date_Captured { get; set; }
        public string Employer_pin { get; set; }
        public string Ownershipdocuments { get; set; }
        public string Incorporationdocument { get; set; }
        public string InstitutionRegDocument { get; set; }
        public string Tsc_Code { get; set; }
        public string Knec_Code { get; set; }
        public string Institution_Sponsor { get; set; }
        public string DEL { get; set; }
        public Nullable<bool> fse { get; set; }
        public string Registration_Date { get; set; }
    }
}
