//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUTION_ASSETS
    {
        public int ID { get; set; }
        public string Institution_Code { get; set; }
        public string Asset_Code { get; set; }
        public string Asset_Name { get; set; }
        public string Asset_Type_Code { get; set; }
        public string Asset_Classification_Code { get; set; }
        public Nullable<System.DateTime> Acquisition_Date { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Cost { get; set; }
        public string Source_of_Funds { get; set; }
        public string Roofing_Material { get; set; }
        public string Wall_Material { get; set; }
        public string Floor_Material { get; set; }
        public string Status_Code { get; set; }
        public string Captured_By { get; set; }
        public Nullable<System.DateTime> Date_Captured { get; set; }
        public string Age { get; set; }
    }
}
