//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUTION_DHIS_TREATMENTDATA_GRADE
    {
        public string Year { get; set; }
        public string DrugID { get; set; }
        public string InstitutionID { get; set; }
        public string Class_Code { get; set; }
        public Nullable<int> M { get; set; }
        public Nullable<int> F { get; set; }
        public Nullable<int> T { get; set; }
        public Nullable<int> boys_2_5 { get; set; }
        public Nullable<int> girls_2_5 { get; set; }
        public Nullable<int> boys_6_plus { get; set; }
        public Nullable<int> girls_6_plus { get; set; }
        public Nullable<int> boys_6_14 { get; set; }
        public Nullable<int> girls_6_14 { get; set; }
        public Nullable<int> boys_15_18 { get; set; }
        public Nullable<int> girls_15_18 { get; set; }
    }
}
