//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUTION_INFRASTRUCTURE_PROJECTS_DOCUMENTS
    {
        public Nullable<int> ProjectID { get; set; }
        public int DocID { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public string Description { get; set; }
        public string FileCode { get; set; }
        public string FileExt { get; set; }
        public string FileContentType { get; set; }
        public string FileName { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
    }
}
