//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUTION_ADMIT_OTHERCLASSES
    {
        public string Institution_Code { get; set; }
        public string Adm_No { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Othername { get; set; }
        public string Gender { get; set; }
        public string Class_Code { get; set; }
        public string YearofKCPE { get; set; }
        public string KCPEIndex { get; set; }
        public string BirthCertificate { get; set; }
        public string Remark { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    }
}
