//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUTION_STAFF_DECEASED
    {
        public string Institution_Code { get; set; }
        public string UPI { get; set; }
        public string Employee_No { get; set; }
        public Nullable<System.DateTime> TSC_Registration_Date { get; set; }
        public string TSC_Reg_Cert_Path { get; set; }
        public string Employee_Type_Code { get; set; }
        public string KRA_PIN { get; set; }
        public string Job_Title { get; set; }
        public string Home_Address { get; set; }
        public string Current_Address { get; set; }
        public string Email_Address { get; set; }
        public string Telephone_No { get; set; }
        public string Home_County_Code { get; set; }
        public string Home_Sub_County_Code { get; set; }
        public string Constituency_Code { get; set; }
        public string Ward_Code { get; set; }
        public Nullable<System.DateTime> Date_of_First_Appointment { get; set; }
        public string TOS_Code { get; set; }
        public string Marital_Status_Code { get; set; }
        public bool Status_Code { get; set; }
        public string Inactive_Reason_Code { get; set; }
        public string Highest_Qualification_Code { get; set; }
        public string Training_Institution_Code { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Captured_By { get; set; }
        public Nullable<System.DateTime> Date_Captured { get; set; }
        public string Ethinicity { get; set; }
        public string Gender { get; set; }
        public string Designation_Code { get; set; }
    }
}
