//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUTION_INFRASTRUCTURE_PROJECTS_DOCUMENT_TYPES
    {
        public int DocumentID { get; set; }
        public string DocumentType { get; set; }
        public string OrderID { get; set; }
    }
}
