//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTEGRATION_EMAIL
    {
        public int ApplicationID { get; set; }
        public int EmailID { get; set; }
        public string EmailSubject { get; set; }
        public string SentToEmail { get; set; }
        public string SentToTitle { get; set; }
        public string SentCopyToEmail { get; set; }
        public string MessageBody { get; set; }
        public string SentFromEmail { get; set; }
        public string SentFromTitle { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UserCategory { get; set; }
    }
}
