//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEARNERS_PROGRESSION_GRADES
    {
        public string Class_Code { get; set; }
        public string Class_Name { get; set; }
        public string Level_Code { get; set; }
        public string Progression_Class_Code { get; set; }
    }
}
