//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEARNER_PARENT_CONTACTS
    {
        public string Class_Code { get; set; }
        public string Class_Name { get; set; }
        public string Father_Name { get; set; }
        public string Father_IDNo { get; set; }
        public string Father_Contacts { get; set; }
        public string Mother_Name { get; set; }
        public string Mother_IDNo { get; set; }
        public string Mother_Contacts { get; set; }
        public string Guardian_Name { get; set; }
        public string Guardian_IDNo { get; set; }
        public string Guardian_Contacts { get; set; }
        public string Father_Email { get; set; }
        public string Mother_Email { get; set; }
        public string Guardian_Email { get; set; }
    }
}
