//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearnerDOBTempDb
    {
        public int ID { get; set; }
        public string UPI { get; set; }
        public string Class_Code { get; set; }
        public string DOB { get; set; }
        public string Processed { get; set; }
    }
}
