//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEARNER_NEW
    {
        public string UPI { get; set; }
        public string Institution_Code { get; set; }
        public string County_Code { get; set; }
        public string Sub_County_Code { get; set; }
        public string Class_Code { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string OtherNames { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ID_No { get; set; }
        public string Birth_Cert_No { get; set; }
        public string Nationality_Code { get; set; }
        public string Gender { get; set; }
        public string Phone_Number { get; set; }
        public string Email_Address { get; set; }
        public string Postal_Address { get; set; }
        public string Disability_Code { get; set; }
        public string Any_Special_Medical_Condition { get; set; }
        public string Special_Medical_Condition { get; set; }
        public Nullable<System.DateTime> Registration_Date { get; set; }
        public string Talent_Code { get; set; }
        public string Talent_Details { get; set; }
        public string Father_UPI { get; set; }
        public string Mother_UPI { get; set; }
        public string Guardian_UPI { get; set; }
        public string Father_Name { get; set; }
        public string Father_IDNo { get; set; }
        public string Father_Contacts { get; set; }
        public string Mother_Name { get; set; }
        public string Mother_IDNo { get; set; }
        public string Mother_Contacts { get; set; }
        public string Guardian_Name { get; set; }
        public string Guardian_IDNo { get; set; }
        public string Guardian_Contacts { get; set; }
        public Nullable<bool> Statusx { get; set; }
        public string Inactive_Reasons_Code { get; set; }
        public string Captured_By { get; set; }
        public Nullable<System.DateTime> Date_Captured { get; set; }
        public string Special_Needs_List { get; set; }
        public string Father_Email { get; set; }
        public string Mother_Email { get; set; }
        public string Guardian_Email { get; set; }
        public Nullable<bool> IsNHIF { get; set; }
        public string NHIF_No { get; set; }
        public string DEL { get; set; }
        public string graduate_Inst { get; set; }
        public string Status { get; set; }
    }
}
