//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public Nullable<int> Q1 { get; set; }
        public string Q1Ans { get; set; }
        public Nullable<int> Q2 { get; set; }
        public string Q2Ans { get; set; }
        public Nullable<int> LoginAttempts { get; set; }
        public Nullable<bool> Locked { get; set; }
    }
}
