//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARITAL_STATUS_TYPES
    {
        public string Marital_Status_Code { get; set; }
        public string Marital_Status_Name { get; set; }
        public Nullable<int> Aid { get; set; }
        public int Idx { get; set; }
    }
}
