//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public string HrefPath { get; set; }
        public string LinkTitle { get; set; }
        public string LinkGroup { get; set; }
        public string AccessLevel { get; set; }
        public string MLevel { get; set; }
        public string ChildLevel { get; set; }
        public string OrderID { get; set; }
        public string Visible { get; set; }
        public string UserLevel { get; set; }
        public string MenuCategory { get; set; }
        public string ReadOnly { get; set; }
        public string MenuType { get; set; }
    }
}
