//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONITORING_TRACKING_ROUTINE_SCHOLARSHIPS_TYPE
    {
        public int SCHOLARSHIPS_TYPE { get; set; }
        public string PeriodIDUIC { get; set; }
        public Nullable<int> NoOfScholarsOrd_M { get; set; }
        public Nullable<int> NoOfScholarsOrd_F { get; set; }
        public Nullable<int> NoOfScholarsSNE_M { get; set; }
        public Nullable<int> NoOfScholarsSNE_F { get; set; }
        public Nullable<int> NoOfScholarsAbsentmorethan25percent_M { get; set; }
        public Nullable<int> NoOfScholarsAbsentmorethan25percent_F { get; set; }
        public string ReasonForAbsenteeism { get; set; }
        public string ReasonForAbsenteeismOther { get; set; }
        public Nullable<int> NoOfScholarsdroppedOutOrd_m { get; set; }
        public Nullable<int> NoOfScholarsdroppedOutOrd_f { get; set; }
        public Nullable<int> NoOfScholarsdroppedOutSNE_m { get; set; }
        public Nullable<int> NoOfScholarsdroppedOutSNE_f { get; set; }
        public string ReasonsforDropOut { get; set; }
        public string ReasonsforDropOutOther { get; set; }
    }
}
