//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NEMISEntities : DbContext
    {
        public NEMISEntities()
            : base("name=NEMISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCESSLOG> ACCESSLOGs { get; set; }
        public virtual DbSet<ADMISSION_DIFFERED_REPORTING> ADMISSION_DIFFERED_REPORTING { get; set; }
        public virtual DbSet<ADMISSION_PROJECTIONS> ADMISSION_PROJECTIONS { get; set; }
        public virtual DbSet<ADMISSION_REPORTED_CAPTURED> ADMISSION_REPORTED_CAPTURED { get; set; }
        public virtual DbSet<ADMISSION_REPORTED_CAPTURED_REMOVE> ADMISSION_REPORTED_CAPTURED_REMOVE { get; set; }
        public virtual DbSet<ADMISSION_REPORTING> ADMISSION_REPORTING { get; set; }
        public virtual DbSet<ADMISSION_REPORTING_TEMP> ADMISSION_REPORTING_TEMP { get; set; }
        public virtual DbSet<ADMISSION_REQUESTS_ON> ADMISSION_REQUESTS_ON { get; set; }
        public virtual DbSet<ADMISSION_REQUESTS_ON_LOG> ADMISSION_REQUESTS_ON_LOG { get; set; }
        public virtual DbSet<ADMISSION_REQUESTS_STAGING> ADMISSION_REQUESTS_STAGING { get; set; }
        public virtual DbSet<ADMISSION_SELECTION> ADMISSION_SELECTION { get; set; }
        public virtual DbSet<ADMISSION_UPLOADS> ADMISSION_UPLOADS { get; set; }
        public virtual DbSet<ADMISSIONATTACHMENT> ADMISSIONATTACHMENTS { get; set; }
        public virtual DbSet<APILogin> APILogins { get; set; }
        public virtual DbSet<ASSET_TYPES> ASSET_TYPES { get; set; }
        public virtual DbSet<ASSETS_DESCRIPTION> ASSETS_DESCRIPTION { get; set; }
        public virtual DbSet<AWARD> AWARDS { get; set; }
        public virtual DbSet<BankAccount> BankAccounts { get; set; }
        public virtual DbSet<BankAccountType> BankAccountTypes { get; set; }
        public virtual DbSet<BANKS_BRANCH> BANKS_BRANCH { get; set; }
        public virtual DbSet<BANKS_REGISTER> BANKS_REGISTER { get; set; }
        public virtual DbSet<BUILDING_MATERIAL> BUILDING_MATERIAL { get; set; }
        public virtual DbSet<CALAMITY> CALAMITies { get; set; }
        public virtual DbSet<CALAMITY_OCCURENCE> CALAMITY_OCCURENCE { get; set; }
        public virtual DbSet<CAPITATION> CAPITATIONs { get; set; }
        public virtual DbSet<CAPITATION_ACCOUNT> CAPITATION_ACCOUNT { get; set; }
        public virtual DbSet<CAPITATION_ACKNOWLEDGEMENT> CAPITATION_ACKNOWLEDGEMENT { get; set; }
        public virtual DbSet<CAPITATION_AUDIT_ANALYSIS> CAPITATION_AUDIT_ANALYSIS { get; set; }
        public virtual DbSet<CAPITATION_AUDIT_ANALYSIS_NEW> CAPITATION_AUDIT_ANALYSIS_NEW { get; set; }
        public virtual DbSet<CAPITATION_ENTITY_DESCRIPTION> CAPITATION_ENTITY_DESCRIPTION { get; set; }
        public virtual DbSet<CAPITATION_ENTITY_FUNDING> CAPITATION_ENTITY_FUNDING { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT> CAPITATION_FINAL_DISBURSEMENT { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_TESTING> CAPITATION_FINAL_DISBURSEMENT_TESTING { get; set; }
        public virtual DbSet<CAPITATION_FINAL_ENROLMENT> CAPITATION_FINAL_ENROLMENT { get; set; }
        public virtual DbSet<CAPITATION_INSTITUTION> CAPITATION_INSTITUTION { get; set; }
        public virtual DbSet<CAPITATION_LEARNERS> CAPITATION_LEARNERS { get; set; }
        public virtual DbSet<CAPITATION_RECONCILE_TRANSACTIONID> CAPITATION_RECONCILE_TRANSACTIONID { get; set; }
        public virtual DbSet<CAPITATION_RECOVERY_DESCRIPTION> CAPITATION_RECOVERY_DESCRIPTION { get; set; }
        public virtual DbSet<CBCCenter> CBCCenters { get; set; }
        public virtual DbSet<CBCEvaluationMatrix> CBCEvaluationMatrices { get; set; }
        public virtual DbSet<CO_CORRICULAR_ACTIVITY> CO_CORRICULAR_ACTIVITY { get; set; }
        public virtual DbSet<CO_CURRICULAR_LEVEL> CO_CURRICULAR_LEVEL { get; set; }
        public virtual DbSet<CONTENTITEM> CONTENTITEMS { get; set; }
        public virtual DbSet<COUNTY> COUNTies { get; set; }
        public virtual DbSet<DASHBOARDITEM> DASHBOARDITEMS { get; set; }
        public virtual DbSet<DATASHEET> DATASHEETs { get; set; }
        public virtual DbSet<DATASHEET_DESKS_SHORTAGE> DATASHEET_DESKS_SHORTAGE { get; set; }
        public virtual DbSet<DATASHEET_DLP_POWER> DATASHEET_DLP_POWER { get; set; }
        public virtual DbSet<DATASHEET_DROPOUTS> DATASHEET_DROPOUTS { get; set; }
        public virtual DbSet<DATASHEET_ENROLMENT> DATASHEET_ENROLMENT { get; set; }
        public virtual DbSet<DATASHEET_PERSONNEL> DATASHEET_PERSONNEL { get; set; }
        public virtual DbSet<DATASHEET_SINGLEPIECE> DATASHEET_SINGLEPIECE { get; set; }
        public virtual DbSet<DATASHEET_SPECIAL_NEEDS> DATASHEET_SPECIAL_NEEDS { get; set; }
        public virtual DbSet<DATASHEET_STREAMS> DATASHEET_STREAMS { get; set; }
        public virtual DbSet<DATASHEET_TEXTBOOKS> DATASHEET_TEXTBOOKS { get; set; }
        public virtual DbSet<DECEASED_REPORTING> DECEASED_REPORTING { get; set; }
        public virtual DbSet<DEF_DROPOUT_REASONS> DEF_DROPOUT_REASONS { get; set; }
        public virtual DbSet<DEF_ELECTRICITY> DEF_ELECTRICITY { get; set; }
        public virtual DbSet<DEF_WATERSOURCE> DEF_WATERSOURCE { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENTS { get; set; }
        public virtual DbSet<DEPARTMENTUSER> DEPARTMENTUSERs { get; set; }
        public virtual DbSet<DEPARTMENTUSERCATEGORy> DEPARTMENTUSERCATEGORIES { get; set; }
        public virtual DbSet<DEVELOPMENT_FUND> DEVELOPMENT_FUND { get; set; }
        public virtual DbSet<DISABILITY> DISABILITies { get; set; }
        public virtual DbSet<DLPLOT> DLPLOTS { get; set; }
        public virtual DbSet<DOUBTFULSCHOOL> DOUBTFULSCHOOLS { get; set; }
        public virtual DbSet<EDUCATION_SYSTEMS> EDUCATION_SYSTEMS { get; set; }
        public virtual DbSet<EMPLOYEE_TYPES> EMPLOYEE_TYPES { get; set; }
        public virtual DbSet<EXPENDITUREITEM> EXPENDITUREITEMS { get; set; }
        public virtual DbSet<FEEITEM> FEEITEMS { get; set; }
        public virtual DbSet<FEE> FEES { get; set; }
        public virtual DbSet<FPEClearedList> FPEClearedLists { get; set; }
        public virtual DbSet<FUND_AGENCY> FUND_AGENCY { get; set; }
        public virtual DbSet<FUND_AGENCY_PROGRAMME> FUND_AGENCY_PROGRAMME { get; set; }
        public virtual DbSet<FUND_AGENCY_PROGRAMME_PAYMENTMODE> FUND_AGENCY_PROGRAMME_PAYMENTMODE { get; set; }
        public virtual DbSet<FUNDING_SOURCE> FUNDING_SOURCE { get; set; }
        public virtual DbSet<INACTIVE_REASONS> INACTIVE_REASONS { get; set; }
        public virtual DbSet<INCOME_RETURN> INCOME_RETURN { get; set; }
        public virtual DbSet<INSTITUTION> INSTITUTIONs { get; set; }
        public virtual DbSet<INSTITUTION_ADMIT_OTHERCLASSES> INSTITUTION_ADMIT_OTHERCLASSES { get; set; }
        public virtual DbSet<INSTITUTION_ADMIT_OTHERCLASSES_FINAL> INSTITUTION_ADMIT_OTHERCLASSES_FINAL { get; set; }
        public virtual DbSet<INSTITUTION_ASSETS> INSTITUTION_ASSETS { get; set; }
        public virtual DbSet<INSTITUTION_CATEGORY> INSTITUTION_CATEGORY { get; set; }
        public virtual DbSet<INSTITUTION_CLUSTERS> INSTITUTION_CLUSTERS { get; set; }
        public virtual DbSet<INSTITUTION_CO_CURRICULAR> INSTITUTION_CO_CURRICULAR { get; set; }
        public virtual DbSet<INSTITUTION_DHIS_DATA> INSTITUTION_DHIS_DATA { get; set; }
        public virtual DbSet<INSTITUTION_DHIS_DATA_GRADE> INSTITUTION_DHIS_DATA_GRADE { get; set; }
        public virtual DbSet<INSTITUTION_DHIS_DRUG> INSTITUTION_DHIS_DRUG { get; set; }
        public virtual DbSet<INSTITUTION_DHIS_LIST> INSTITUTION_DHIS_LIST { get; set; }
        public virtual DbSet<INSTITUTION_DHIS_TREATMENTDATA> INSTITUTION_DHIS_TREATMENTDATA { get; set; }
        public virtual DbSet<INSTITUTION_DHIS_TREATMENTDATA_GRADE> INSTITUTION_DHIS_TREATMENTDATA_GRADE { get; set; }
        public virtual DbSet<INSTITUTION_GENDER> INSTITUTION_GENDER { get; set; }
        public virtual DbSet<INSTITUTION_GEOADDRESS> INSTITUTION_GEOADDRESS { get; set; }
        public virtual DbSet<INSTITUTION_INFRASTRUCTURE_PROGRESS_STATUS> INSTITUTION_INFRASTRUCTURE_PROGRESS_STATUS { get; set; }
        public virtual DbSet<INSTITUTION_INFRASTRUCTURE_PROJECTS> INSTITUTION_INFRASTRUCTURE_PROJECTS { get; set; }
        public virtual DbSet<INSTITUTION_INFRASTRUCTURE_PROJECTS_DETAIL> INSTITUTION_INFRASTRUCTURE_PROJECTS_DETAIL { get; set; }
        public virtual DbSet<INSTITUTION_INFRASTRUCTURE_PROJECTS_DOCUMENT_TYPES> INSTITUTION_INFRASTRUCTURE_PROJECTS_DOCUMENT_TYPES { get; set; }
        public virtual DbSet<INSTITUTION_INFRASTRUCTURE_PROJECTS_DOCUMENTS> INSTITUTION_INFRASTRUCTURE_PROJECTS_DOCUMENTS { get; set; }
        public virtual DbSet<INSTITUTION_INFRASTRUCTURE_PROJECTS_PAYMENTS> INSTITUTION_INFRASTRUCTURE_PROJECTS_PAYMENTS { get; set; }
        public virtual DbSet<INSTITUTION_LEARNERS_SUMMARIES> INSTITUTION_LEARNERS_SUMMARIES { get; set; }
        public virtual DbSet<INSTITUTION_MOBILITY> INSTITUTION_MOBILITY { get; set; }
        public virtual DbSet<INSTITUTION_NAME_CHANGE> INSTITUTION_NAME_CHANGE { get; set; }
        public virtual DbSet<INSTITUTION_NAME_CHANGE_DONE> INSTITUTION_NAME_CHANGE_DONE { get; set; }
        public virtual DbSet<INSTITUTION_OWNERSHIP_DOCUMENT> INSTITUTION_OWNERSHIP_DOCUMENT { get; set; }
        public virtual DbSet<INSTITUTION_PREMISE_OWNERSHIP> INSTITUTION_PREMISE_OWNERSHIP { get; set; }
        public virtual DbSet<INSTITUTION_PROPRIETOR> INSTITUTION_PROPRIETOR { get; set; }
        public virtual DbSet<INSTITUTION_REPORTED_CASES> INSTITUTION_REPORTED_CASES { get; set; }
        public virtual DbSet<INSTITUTION_REPORTED_CLASS> INSTITUTION_REPORTED_CLASS { get; set; }
        public virtual DbSet<INSTITUTION_REPORTED_CLASS_REP> INSTITUTION_REPORTED_CLASS_REP { get; set; }
        public virtual DbSet<INSTITUTION_REPORTED_FAIL_CAUSES> INSTITUTION_REPORTED_FAIL_CAUSES { get; set; }
        public virtual DbSet<INSTITUTION_REPORTED_FAILED_REASONS> INSTITUTION_REPORTED_FAILED_REASONS { get; set; }
        public virtual DbSet<INSTITUTION_SUMMARIES> INSTITUTION_SUMMARIES { get; set; }
        public virtual DbSet<INSTITUTION_UTILITY> INSTITUTION_UTILITY { get; set; }
        public virtual DbSet<INSTITUTION_WASH> INSTITUTION_WASH { get; set; }
        public virtual DbSet<INSTITUTION_WASH_HYG> INSTITUTION_WASH_HYG { get; set; }
        public virtual DbSet<INSTITUTION_WASH_SAN> INSTITUTION_WASH_SAN { get; set; }
        public virtual DbSet<INSTITUTION_WASH_WATER> INSTITUTION_WASH_WATER { get; set; }
        public virtual DbSet<INSTITUTIONEXPENDITURE> INSTITUTIONEXPENDITUREs { get; set; }
        public virtual DbSet<INTEGRATION_EMAIL> INTEGRATION_EMAIL { get; set; }
        public virtual DbSet<INTEGRATION_SMS> INTEGRATION_SMS { get; set; }
        public virtual DbSet<INTEGRATIONMASTER> INTEGRATIONMASTERs { get; set; }
        public virtual DbSet<LEARNER> LEARNERs { get; set; }
        public virtual DbSet<LEARNER_ALUMNI> LEARNER_ALUMNI { get; set; }
        public virtual DbSet<LEARNER_DECEASED> LEARNER_DECEASED { get; set; }
        public virtual DbSet<LEARNER_DROPOUT> LEARNER_DROPOUT { get; set; }
        public virtual DbSet<LEARNER_MOBILITY_TYPES> LEARNER_MOBILITY_TYPES { get; set; }
        public virtual DbSet<LEARNER_NEW> LEARNER_NEW { get; set; }
        public virtual DbSet<LEARNER_NEW_CONTACTS> LEARNER_NEW_CONTACTS { get; set; }
        public virtual DbSet<LEARNER_NEW_TMP> LEARNER_NEW_TMP { get; set; }
        public virtual DbSet<LEARNER_NEW_TMP2> LEARNER_NEW_TMP2 { get; set; }
        public virtual DbSet<LEARNER_TRANSFER_GRADE> LEARNER_TRANSFER_GRADE { get; set; }
        public virtual DbSet<LEARNER_TRANSFER_GRADE_log> LEARNER_TRANSFER_GRADE_log { get; set; }
        public virtual DbSet<LEARNER_TRANSITION> LEARNER_TRANSITION { get; set; }
        public virtual DbSet<LEARNERS_PROGRESSION> LEARNERS_PROGRESSION { get; set; }
        public virtual DbSet<LEARNERS_PROGRESSION_GRADES> LEARNERS_PROGRESSION_GRADES { get; set; }
        public virtual DbSet<LEARNERSLEVEL> LEARNERSLEVELs { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<LOGINLOG> LOGINLOGs { get; set; }
        public virtual DbSet<MENU> MENUS { get; set; }
        public virtual DbSet<moe_nhif_data> moe_nhif_data { get; set; }
        public virtual DbSet<moe_nhif_data_inquiry> moe_nhif_data_inquiry { get; set; }
        public virtual DbSet<moe_nhif_data_removed> moe_nhif_data_removed { get; set; }
        public virtual DbSet<moe_nhif_data_update> moe_nhif_data_update { get; set; }
        public virtual DbSet<MONITORING_DELIVERABLES_STATIC> MONITORING_DELIVERABLES_STATIC { get; set; }
        public virtual DbSet<MONITORING_TRACKING_ROUTINE> MONITORING_TRACKING_ROUTINE { get; set; }
        public virtual DbSet<MONITORING_TRACKING_ROUTINE_ADVOCACY> MONITORING_TRACKING_ROUTINE_ADVOCACY { get; set; }
        public virtual DbSet<MONITORING_TRACKING_ROUTINE_SCHOLARSHIP> MONITORING_TRACKING_ROUTINE_SCHOLARSHIP { get; set; }
        public virtual DbSet<MONITORING_TRACKING_ROUTINE_SCHOLARSHIPS_TYPE> MONITORING_TRACKING_ROUTINE_SCHOLARSHIPS_TYPE { get; set; }
        public virtual DbSet<NATIONALITY> NATIONALITies { get; set; }
        public virtual DbSet<new_nhif_data> new_nhif_data { get; set; }
        public virtual DbSet<nhif_student_data> nhif_student_data { get; set; }
        public virtual DbSet<nhif_student_data_remove> nhif_student_data_remove { get; set; }
        public virtual DbSet<nhif_student_treatment> nhif_student_treatment { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<PERSON> PERSONS { get; set; }
        public virtual DbSet<PERSONS_ALUMNI> PERSONS_ALUMNI { get; set; }
        public virtual DbSet<PERSONS_DECEASED> PERSONS_DECEASED { get; set; }
        public virtual DbSet<PERSONS_NEW> PERSONS_NEW { get; set; }
        public virtual DbSet<PROGRAMME> PROGRAMMEs { get; set; }
        public virtual DbSet<PROJECT_EXPENDITURE> PROJECT_EXPENDITURE { get; set; }
        public virtual DbSet<PROPRIETOR> PROPRIETORs { get; set; }
        public virtual DbSet<QUALIFICATION_TYPE> QUALIFICATION_TYPE { get; set; }
        public virtual DbSet<REGION> REGIONs { get; set; }
        public virtual DbSet<REGIONUSER> REGIONUSERs { get; set; }
        public virtual DbSet<ROLE> ROLES { get; set; }
        public virtual DbSet<SMPApprovalCycle> SMPApprovalCycles { get; set; }
        public virtual DbSet<SMPCashCashOtherFunding> SMPCashCashOtherFundings { get; set; }
        public virtual DbSet<SMPCashOtherDescription> SMPCashOtherDescriptions { get; set; }
        public virtual DbSet<SMPCategoryLookUp> SMPCategoryLookUps { get; set; }
        public virtual DbSet<SMPFoodBasketCategory> SMPFoodBasketCategories { get; set; }
        public virtual DbSet<SMPFoodConsumptionLookup> SMPFoodConsumptionLookups { get; set; }
        public virtual DbSet<SMPFoodItem> SMPFoodItems { get; set; }
        public virtual DbSet<SMPFoodItemsPurchaseOrder> SMPFoodItemsPurchaseOrders { get; set; }
        public virtual DbSet<SMPFoodItemsSupplied> SMPFoodItemsSupplieds { get; set; }
        public virtual DbSet<SMPFoodLookUp> SMPFoodLookUps { get; set; }
        public virtual DbSet<SMPFoodLookUpUsed> SMPFoodLookUpUseds { get; set; }
        public virtual DbSet<SMPFoodPackageGradeLookup> SMPFoodPackageGradeLookups { get; set; }
        public virtual DbSet<SMPFoodPackageLookup> SMPFoodPackageLookups { get; set; }
        public virtual DbSet<SMPFoodUnitOfMeasureLookup> SMPFoodUnitOfMeasureLookups { get; set; }
        public virtual DbSet<SMPFundType> SMPFundTypes { get; set; }
        public virtual DbSet<SMPSchoolCashFunding> SMPSchoolCashFundings { get; set; }
        public virtual DbSet<SMPSchoolDailyAttendance> SMPSchoolDailyAttendances { get; set; }
        public virtual DbSet<SMPSchoolDailyAttendanceComplete> SMPSchoolDailyAttendanceCompletes { get; set; }
        public virtual DbSet<SMPSchoolDailyFoodRelease> SMPSchoolDailyFoodReleases { get; set; }
        public virtual DbSet<SMPSchoolDailyFoodReleaseForCash> SMPSchoolDailyFoodReleaseForCashes { get; set; }
        public virtual DbSet<SMPSchoolEnrolment> SMPSchoolEnrolments { get; set; }
        public virtual DbSet<SMPSchoolProcurementPlanForCash> SMPSchoolProcurementPlanForCashes { get; set; }
        public virtual DbSet<SMPSchoolRecieveProcuredFoodItemsForCash> SMPSchoolRecieveProcuredFoodItemsForCashes { get; set; }
        public virtual DbSet<SMPSchool> SMPSchools { get; set; }
        public virtual DbSet<SMPSchools_Final_Disbursement> SMPSchools_Final_Disbursement { get; set; }
        public virtual DbSet<SMPSchools_Learners> SMPSchools_Learners { get; set; }
        public virtual DbSet<SMPSchoolsBankAccount> SMPSchoolsBankAccounts { get; set; }
        public virtual DbSet<SMPSchoolsDeliveryNote> SMPSchoolsDeliveryNotes { get; set; }
        public virtual DbSet<SMPSchoolsDeliveryNotesFoodItem> SMPSchoolsDeliveryNotesFoodItems { get; set; }
        public virtual DbSet<SMPSchoolsFoodItem> SMPSchoolsFoodItems { get; set; }
        public virtual DbSet<SMPSchoolStore> SMPSchoolStores { get; set; }
        public virtual DbSet<SMPSchoolStoreForCash> SMPSchoolStoreForCashes { get; set; }
        public virtual DbSet<SMPSubCountyRoutesLookUp> SMPSubCountyRoutesLookUps { get; set; }
        public virtual DbSet<SMPSubCountyTransportersLookUp> SMPSubCountyTransportersLookUps { get; set; }
        public virtual DbSet<SMPSubCountyWarehous> SMPSubCountyWarehouses { get; set; }
        public virtual DbSet<SMPSuppliersLookUp> SMPSuppliersLookUps { get; set; }
        public virtual DbSet<SMPTermLookUp> SMPTermLookUps { get; set; }
        public virtual DbSet<SMPTransporterLookup> SMPTransporterLookups { get; set; }
        public virtual DbSet<SMPVehiclesLookup> SMPVehiclesLookups { get; set; }
        public virtual DbSet<SMPWaybillBasic> SMPWaybillBasics { get; set; }
        public virtual DbSet<SMPWayBillDetail> SMPWayBillDetails { get; set; }
        public virtual DbSet<ST_DESIGNATIONS> ST_DESIGNATIONS { get; set; }
        public virtual DbSet<STAFF_MOBILITY_TYPES> STAFF_MOBILITY_TYPES { get; set; }
        public virtual DbSet<STATIC_REGISTER_QUESTION> STATIC_REGISTER_QUESTION { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
        public virtual DbSet<STUDY_AREA> STUDY_AREA { get; set; }
        public virtual DbSet<SUB_COUNTY> SUB_COUNTY { get; set; }
        public virtual DbSet<SUBJECT> SUBJECTs { get; set; }
        public virtual DbSet<SUBMENUROLE> SUBMENUROLEs { get; set; }
        public virtual DbSet<SUBMENU> SUBMENUS { get; set; }
        public virtual DbSet<System_parameters> System_parameters { get; set; }
        public virtual DbSet<SYSTEMLOG> SYSTEMLOGS { get; set; }
        public virtual DbSet<SYSTEMLOGSMASTER> SYSTEMLOGSMASTERs { get; set; }
        public virtual DbSet<TALENT_TYPE> TALENT_TYPE { get; set; }
        public virtual DbSet<TEACHERS_RESPONSIBILITY> TEACHERS_RESPONSIBILITY { get; set; }
        public virtual DbSet<TEACHING_AREAS> TEACHING_AREAS { get; set; }
        public virtual DbSet<TEACHING_MATERIALS> TEACHING_MATERIALS { get; set; }
        public virtual DbSet<TERM_OF_SERVICE> TERM_OF_SERVICE { get; set; }
        public virtual DbSet<UPI_GENERATOR> UPI_GENERATOR { get; set; }
        public virtual DbSet<UPI_USED> UPI_USED { get; set; }
        public virtual DbSet<USERCATEGORY> USERCATEGORies { get; set; }
        public virtual DbSet<USERROLEASSIGNMENT> USERROLEASSIGNMENTs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UTILITy> UTILITIES { get; set; }
        public virtual DbSet<ACTIVITY_LEVEL> ACTIVITY_LEVEL { get; set; }
        public virtual DbSet<ADMISSION_DATES> ADMISSION_DATES { get; set; }
        public virtual DbSet<ADMISSION_LOGS> ADMISSION_LOGS { get; set; }
        public virtual DbSet<ADMISSION_LOGS_ARCHIVE> ADMISSION_LOGS_ARCHIVE { get; set; }
        public virtual DbSet<ADMISSION_REPORTED_CAPTURED_ARCHIVE> ADMISSION_REPORTED_CAPTURED_ARCHIVE { get; set; }
        public virtual DbSet<ADMISSION_REPORTING_ARCHIVE> ADMISSION_REPORTING_ARCHIVE { get; set; }
        public virtual DbSet<ADMISSION_REPORTINGBACKUP21JAN> ADMISSION_REPORTINGBACKUP21JAN { get; set; }
        public virtual DbSet<ADMISSION_REQUESTS> ADMISSION_REQUESTS { get; set; }
        public virtual DbSet<ADMISSION_REQUESTS_ARCHIVE> ADMISSION_REQUESTS_ARCHIVE { get; set; }
        public virtual DbSet<ADMISSION_REQUESTS_BACKUP_11AUG2021> ADMISSION_REQUESTS_BACKUP_11AUG2021 { get; set; }
        public virtual DbSet<ADMISSION_REQUESTS_KNOCK_OFF> ADMISSION_REQUESTS_KNOCK_OFF { get; set; }
        public virtual DbSet<ADMISSION_REQUESTS_KNOCK_OFF_ARCHIVE> ADMISSION_REQUESTS_KNOCK_OFF_ARCHIVE { get; set; }
        public virtual DbSet<ADMISSION_REQUESTS_OPEN> ADMISSION_REQUESTS_OPEN { get; set; }
        public virtual DbSet<ADMISSION_REQUESTS_OPEN_ARCHIVE> ADMISSION_REQUESTS_OPEN_ARCHIVE { get; set; }
        public virtual DbSet<ADMISSION_REQUESTS_PUBLIC> ADMISSION_REQUESTS_PUBLIC { get; set; }
        public virtual DbSet<ADMISSION_REQUESTSTEMP> ADMISSION_REQUESTSTEMP { get; set; }
        public virtual DbSet<ADMISSION_REQUESTSTEMP_ARCHIVE> ADMISSION_REQUESTSTEMP_ARCHIVE { get; set; }
        public virtual DbSet<ADMISSION_SELECTION2> ADMISSION_SELECTION2 { get; set; }
        public virtual DbSet<ADMISSION_SELECTION2_DONE> ADMISSION_SELECTION2_DONE { get; set; }
        public virtual DbSet<ASSET_CLASSIFICATION> ASSET_CLASSIFICATION { get; set; }
        public virtual DbSet<ASSET_STATUS> ASSET_STATUS { get; set; }
        public virtual DbSet<BankAccounts_DEL> BankAccounts_DEL { get; set; }
        public virtual DbSet<CALAMITY_STATUS> CALAMITY_STATUS { get; set; }
        public virtual DbSet<CAPITATION_ACCOUNT_MISSED> CAPITATION_ACCOUNT_MISSED { get; set; }
        public virtual DbSet<CAPITATION_ACCOUNT_MISSED2> CAPITATION_ACCOUNT_MISSED2 { get; set; }
        public virtual DbSet<CAPITATION_ERROR_RECOVERIES> CAPITATION_ERROR_RECOVERIES { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_14May2019> CAPITATION_FINAL_DISBURSEMENT_14May2019 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_2019_DETAILED> CAPITATION_FINAL_DISBURSEMENT_2019_DETAILED { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_2020_RecoveriesFor2019Excesses> CAPITATION_FINAL_DISBURSEMENT_2020_RecoveriesFor2019Excesses { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_BACK_SEPT2019> CAPITATION_FINAL_DISBURSEMENT_BACK_SEPT2019 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_BACKUP_10June2019> CAPITATION_FINAL_DISBURSEMENT_BACKUP_10June2019 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_BACKUP_12APR> CAPITATION_FINAL_DISBURSEMENT_BACKUP_12APR { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_BACKUP13Aug2020> CAPITATION_FINAL_DISBURSEMENT_BACKUP13Aug2020 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_BAKCUPOCT2020> CAPITATION_FINAL_DISBURSEMENT_BAKCUPOCT2020 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_BASE2019> CAPITATION_FINAL_DISBURSEMENT_BASE2019 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_Details> CAPITATION_FINAL_DISBURSEMENT_Details { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_DRAFT0> CAPITATION_FINAL_DISBURSEMENT_DRAFT0 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_DRATFT3> CAPITATION_FINAL_DISBURSEMENT_DRATFT3 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_Final_24April2019> CAPITATION_FINAL_DISBURSEMENT_Final_24April2019 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_JULY2019_BACKUP> CAPITATION_FINAL_DISBURSEMENT_JULY2019_BACKUP { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_JULY2020Details> CAPITATION_FINAL_DISBURSEMENT_JULY2020Details { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_MAY2019Details222> CAPITATION_FINAL_DISBURSEMENT_MAY2019Details222 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_MAY2019Details25April> CAPITATION_FINAL_DISBURSEMENT_MAY2019Details25April { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_MAY2019Details333> CAPITATION_FINAL_DISBURSEMENT_MAY2019Details333 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_MAY2019Details444> CAPITATION_FINAL_DISBURSEMENT_MAY2019Details444 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_MAY2019Details6666> CAPITATION_FINAL_DISBURSEMENT_MAY2019Details6666 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_MAY2019Details7777> CAPITATION_FINAL_DISBURSEMENT_MAY2019Details7777 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_MAY2019DetailsSHULE> CAPITATION_FINAL_DISBURSEMENT_MAY2019DetailsSHULE { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_MAY2019DetailsX> CAPITATION_FINAL_DISBURSEMENT_MAY2019DetailsX { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_MAY2019DetailsX123> CAPITATION_FINAL_DISBURSEMENT_MAY2019DetailsX123 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_MAY2019DetailsXX> CAPITATION_FINAL_DISBURSEMENT_MAY2019DetailsXX { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_MAY2019Detailsxx123> CAPITATION_FINAL_DISBURSEMENT_MAY2019Detailsxx123 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_MAY2019Detailsxxx> CAPITATION_FINAL_DISBURSEMENT_MAY2019Detailsxxx { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_OCT2020Variance> CAPITATION_FINAL_DISBURSEMENT_OCT2020Variance { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_REIMBURSEMENT> CAPITATION_FINAL_DISBURSEMENT_REIMBURSEMENT { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_SEP2019BACK8DEC2020> CAPITATION_FINAL_DISBURSEMENT_SEP2019BACK8DEC2020 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_SEPT_COMPUTED_27AUG2019> CAPITATION_FINAL_DISBURSEMENT_SEPT_COMPUTED_27AUG2019 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_TRANSITION> CAPITATION_FINAL_DISBURSEMENT_TRANSITION { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_TRANSITION_JULY2019> CAPITATION_FINAL_DISBURSEMENT_TRANSITION_JULY2019 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_DISBURSEMENT_TRANSITION_SEPT_DETAILED2> CAPITATION_FINAL_DISBURSEMENT_TRANSITION_SEPT_DETAILED2 { get; set; }
        public virtual DbSet<CAPITATION_FINAL_MISSED_FROM_MAY> CAPITATION_FINAL_MISSED_FROM_MAY { get; set; }
        public virtual DbSet<CAPITATION_FINAL_MISSED_SCHOOLS> CAPITATION_FINAL_MISSED_SCHOOLS { get; set; }
        public virtual DbSet<CAPITATION_FUND> CAPITATION_FUND { get; set; }
        public virtual DbSet<CAPITATION_FUND_FINAL> CAPITATION_FUND_FINAL { get; set; }
        public virtual DbSet<CAPITATION_INSTITUTION2> CAPITATION_INSTITUTION2 { get; set; }
        public virtual DbSet<CAPITATION_LEARNERS_HCOUNT> CAPITATION_LEARNERS_HCOUNT { get; set; }
        public virtual DbSet<CAPITATION_LEARNERS_HIGHCOUNT> CAPITATION_LEARNERS_HIGHCOUNT { get; set; }
        public virtual DbSet<CAPITATION_LEARNERS_HIGHCOUNT2> CAPITATION_LEARNERS_HIGHCOUNT2 { get; set; }
        public virtual DbSet<CAPITATION_LEARNERS_HIGHCOUNT3> CAPITATION_LEARNERS_HIGHCOUNT3 { get; set; }
        public virtual DbSet<CAPITATION_LEARNERS_LCOUNT> CAPITATION_LEARNERS_LCOUNT { get; set; }
        public virtual DbSet<CAPITATION_LEARNERS_LOWCOUNT> CAPITATION_LEARNERS_LOWCOUNT { get; set; }
        public virtual DbSet<CAPITATION_LEARNERS_LOWCOUNT2> CAPITATION_LEARNERS_LOWCOUNT2 { get; set; }
        public virtual DbSet<CAPITATION_LEARNERS_REMOVED7DEC2020> CAPITATION_LEARNERS_REMOVED7DEC2020 { get; set; }
        public virtual DbSet<CAPITATION_RECOVERIES> CAPITATION_RECOVERIES { get; set; }
        public virtual DbSet<CAPITATION_RECOVERIES_AUG2019> CAPITATION_RECOVERIES_AUG2019 { get; set; }
        public virtual DbSet<CAPITATION_RECOVERIES_AUG2019_IMPLEMENT> CAPITATION_RECOVERIES_AUG2019_IMPLEMENT { get; set; }
        public virtual DbSet<CAPITATION_RECOVERIES_DEC2019> CAPITATION_RECOVERIES_DEC2019 { get; set; }
        public virtual DbSet<CAPITATION_RECOVERIES_MAY2019> CAPITATION_RECOVERIES_MAY2019 { get; set; }
        public virtual DbSet<CAPITATION_RECOVERY_AMOUNT> CAPITATION_RECOVERY_AMOUNT { get; set; }
        public virtual DbSet<CAPITATION_RECOVERY_AMOUNT_BACKUP_12APR> CAPITATION_RECOVERY_AMOUNT_BACKUP_12APR { get; set; }
        public virtual DbSet<CAPITATION_RECOVERY_AMOUNT_BACKUP_24April2019> CAPITATION_RECOVERY_AMOUNT_BACKUP_24April2019 { get; set; }
        public virtual DbSet<CAPITATION_RECOVERY_AMOUNT_DIRTY_24April2019> CAPITATION_RECOVERY_AMOUNT_DIRTY_24April2019 { get; set; }
        public virtual DbSet<CAPITATION_RECOVERY_AMOUNT_Draft2> CAPITATION_RECOVERY_AMOUNT_Draft2 { get; set; }
        public virtual DbSet<CAPITATION_RECOVERY_AMOUNT_DRAFT3> CAPITATION_RECOVERY_AMOUNT_DRAFT3 { get; set; }
        public virtual DbSet<CAPITATION_RECOVERY_AMOUNT_NEWEFFECT> CAPITATION_RECOVERY_AMOUNT_NEWEFFECT { get; set; }
        public virtual DbSet<CAPITATION_RECOVERY_AMOUNT_SEPTEMBER_AUDITREC2> CAPITATION_RECOVERY_AMOUNT_SEPTEMBER_AUDITREC2 { get; set; }
        public virtual DbSet<CAPITATION_RECOVERY_REIMBURSEMENT_Details> CAPITATION_RECOVERY_REIMBURSEMENT_Details { get; set; }
        public virtual DbSet<CAPITATION_RECOVERY_WHOLEAMOUNT> CAPITATION_RECOVERY_WHOLEAMOUNT { get; set; }
        public virtual DbSet<CAPITATION_VERIFY> CAPITATION_VERIFY { get; set; }
        public virtual DbSet<CAPITATION_VERIFY2> CAPITATION_VERIFY2 { get; set; }
        public virtual DbSet<CLASS> CLASSes { get; set; }
        public virtual DbSet<CONSTITUENCY> CONSTITUENCies { get; set; }
        public virtual DbSet<COUNTRY> COUNTRies { get; set; }
        public virtual DbSet<COUNTYDLPII> COUNTYDLPIIs { get; set; }
        public virtual DbSet<COURSE> COURSEs { get; set; }
        public virtual DbSet<DEL_INSTITUTION> DEL_INSTITUTION { get; set; }
        public virtual DbSet<DELETED_INSTITUTION> DELETED_INSTITUTION { get; set; }
        public virtual DbSet<DELETED_LEARNERS> DELETED_LEARNERS { get; set; }
        public virtual DbSet<ETHNICITY> ETHNICITies { get; set; }
        public virtual DbSet<EXAMINER> EXAMINERs { get; set; }
        public virtual DbSet<GRADE> GRADEs { get; set; }
        public virtual DbSet<INSTITUTION_ACCOMMODATION> INSTITUTION_ACCOMMODATION { get; set; }
        public virtual DbSet<INSTITUTION_EDUCATION_SYSTEM> INSTITUTION_EDUCATION_SYSTEM { get; set; }
        public virtual DbSet<INSTITUTION_FORMALITY> INSTITUTION_FORMALITY { get; set; }
        public virtual DbSet<INSTITUTION_LEVEL> INSTITUTION_LEVEL { get; set; }
        public virtual DbSet<INSTITUTION_RESIDENCE> INSTITUTION_RESIDENCE { get; set; }
        public virtual DbSet<INSTITUTION_STAFF> INSTITUTION_STAFF { get; set; }
        public virtual DbSet<INSTITUTION_STAFF_DECEASED> INSTITUTION_STAFF_DECEASED { get; set; }
        public virtual DbSet<INSTITUTION_STAFF_DEL> INSTITUTION_STAFF_DEL { get; set; }
        public virtual DbSet<INSTITUTION_STAFF_NEW> INSTITUTION_STAFF_NEW { get; set; }
        public virtual DbSet<INSTITUTION_STAFF_ONMOBILITY> INSTITUTION_STAFF_ONMOBILITY { get; set; }
        public virtual DbSet<INSTITUTION_STAFFX> INSTITUTION_STAFFX { get; set; }
        public virtual DbSet<INSTITUTION_STATUS> INSTITUTION_STATUS { get; set; }
        public virtual DbSet<INSTITUTION_TERM> INSTITUTION_TERM { get; set; }
        public virtual DbSet<INSTITUTION_TYPES> INSTITUTION_TYPES { get; set; }
        public virtual DbSet<Instution_Sponsor> Instution_Sponsor { get; set; }
        public virtual DbSet<LEARNER_BACKUP> LEARNER_BACKUP { get; set; }
        public virtual DbSet<LEARNER_DEL> LEARNER_DEL { get; set; }
        public virtual DbSet<LEARNER_DIRTY> LEARNER_DIRTY { get; set; }
        public virtual DbSet<LEARNER_DIRTY_ORPHAN> LEARNER_DIRTY_ORPHAN { get; set; }
        public virtual DbSet<LEARNER_MOBILITY> LEARNER_MOBILITY { get; set; }
        public virtual DbSet<LEARNER_MOBILITY_END> LEARNER_MOBILITY_END { get; set; }
        public virtual DbSet<LEARNER_NEW_Arc> LEARNER_NEW_Arc { get; set; }
        public virtual DbSet<LEARNER_NEW_CONTACTS_Arc> LEARNER_NEW_CONTACTS_Arc { get; set; }
        public virtual DbSet<LEARNER_NEW_TMP_Arc> LEARNER_NEW_TMP_Arc { get; set; }
        public virtual DbSet<LEARNER_PARENT_CONTACTS> LEARNER_PARENT_CONTACTS { get; set; }
        public virtual DbSet<LEARNER_PERFORMANCE> LEARNER_PERFORMANCE { get; set; }
        public virtual DbSet<LEARNER_SECSTUD> LEARNER_SECSTUD { get; set; }
        public virtual DbSet<LEARNER_SECSTUD_MISSING> LEARNER_SECSTUD_MISSING { get; set; }
        public virtual DbSet<LEARNER_WITHOUT_BC> LEARNER_WITHOUT_BC { get; set; }
        public virtual DbSet<LEARNER_WITHOUT_BC_DEL> LEARNER_WITHOUT_BC_DEL { get; set; }
        public virtual DbSet<LearnerDOBTempDb> LearnerDOBTempDbs { get; set; }
        public virtual DbSet<LEARNERMISSED> LEARNERMISSEDs { get; set; }
        public virtual DbSet<LEARNERS_CLEANING_JPCT> LEARNERS_CLEANING_JPCT { get; set; }
        public virtual DbSet<LEARNERS_LATEST_EXITED> LEARNERS_LATEST_EXITED { get; set; }
        public virtual DbSet<MARITAL_STATUS_TYPES> MARITAL_STATUS_TYPES { get; set; }
        public virtual DbSet<moe_person_data_inquiry> moe_person_data_inquiry { get; set; }
        public virtual DbSet<MONITORING_ADVOCACY_STATIC> MONITORING_ADVOCACY_STATIC { get; set; }
        public virtual DbSet<MONITORING_PERIOD> MONITORING_PERIOD { get; set; }
        public virtual DbSet<MONITORING_SCHOLARSHIPS> MONITORING_SCHOLARSHIPS { get; set; }
        public virtual DbSet<MYDASHBOARD> MYDASHBOARDs { get; set; }
        public virtual DbSet<NewNHIFData> NewNHIFDatas { get; set; }
        public virtual DbSet<PERSONS_BACKUP> PERSONS_BACKUP { get; set; }
        public virtual DbSet<PERSONS_DEL> PERSONS_DEL { get; set; }
        public virtual DbSet<PERSONS_DUPLICATION_FEB2019> PERSONS_DUPLICATION_FEB2019 { get; set; }
        public virtual DbSet<PERSONS_NEW_Arc> PERSONS_NEW_Arc { get; set; }
        public virtual DbSet<PERSONS_STRAY_CAPITATION> PERSONS_STRAY_CAPITATION { get; set; }
        public virtual DbSet<PERSONS_STRAY_CAPITATION_REMOVED> PERSONS_STRAY_CAPITATION_REMOVED { get; set; }
        public virtual DbSet<PROJECT_STATUS> PROJECT_STATUS { get; set; }
        public virtual DbSet<REGIONUSER2> REGIONUSER2 { get; set; }
        public virtual DbSet<RESPONSIBILITy> RESPONSIBILITIES { get; set; }
        public virtual DbSet<SMPCashCashOtherFunding_DEL> SMPCashCashOtherFunding_DEL { get; set; }
        public virtual DbSet<SMPCashCashOtherFunding_Detailed> SMPCashCashOtherFunding_Detailed { get; set; }
        public virtual DbSet<SMPFoodItemsDeleted> SMPFoodItemsDeleteds { get; set; }
        public virtual DbSet<SMPSchools_Final_Disbursement_Detailed> SMPSchools_Final_Disbursement_Detailed { get; set; }
        public virtual DbSet<SMPSchoolsFoodItemsDetailed> SMPSchoolsFoodItemsDetaileds { get; set; }
        public virtual DbSet<SMPSchoolsFoodItemsDetailed_PackageGrade> SMPSchoolsFoodItemsDetailed_PackageGrade { get; set; }
        public virtual DbSet<SMPSchoolsLog> SMPSchoolsLogs { get; set; }
        public virtual DbSet<SPECIAL_MEDICAL_CONDITION_TYPE> SPECIAL_MEDICAL_CONDITION_TYPE { get; set; }
        public virtual DbSet<SPECIAL_NEEDS> SPECIAL_NEEDS { get; set; }
        public virtual DbSet<STAFF_MOBILITY> STAFF_MOBILITY { get; set; }
        public virtual DbSet<STAFF_QUALIFICATIONS> STAFF_QUALIFICATIONS { get; set; }
        public virtual DbSet<STATUS_TYPE> STATUS_TYPE { get; set; }
        public virtual DbSet<TALENT> TALENTS { get; set; }
        public virtual DbSet<TEMPCAPDATA> TEMPCAPDATAs { get; set; }
        public virtual DbSet<TERM> TERMS { get; set; }
        public virtual DbSet<TRAINING_INSTITUTIONS> TRAINING_INSTITUTIONS { get; set; }
        public virtual DbSet<UNCAPTUREDREPORTED> UNCAPTUREDREPORTEDs { get; set; }
        public virtual DbSet<UNCAPTUREDREPORTED2> UNCAPTUREDREPORTED2 { get; set; }
        public virtual DbSet<UNCAPTUREDREPORTED2_RETURN> UNCAPTUREDREPORTED2_RETURN { get; set; }
        public virtual DbSet<UTUMISHI_DEL> UTUMISHI_DEL { get; set; }
        public virtual DbSet<WARD> WARDS { get; set; }
        public virtual DbSet<ZONE> ZONEs { get; set; }
        public virtual DbSet<vw_MyLearner> vw_MyLearner { get; set; }
        public virtual DbSet<vwAdmission> vwAdmissions { get; set; }
        public virtual DbSet<vwLearner> vwLearners { get; set; }
        public virtual DbSet<vwLearnerScholarship> vwLearnerScholarships { get; set; }
    
        public virtual ObjectResult<proc_Get_Categories_Result> proc_Get_Categories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_Categories_Result>("proc_Get_Categories");
        }
    
        public virtual ObjectResult<proc_GetMainMenu_Result> proc_GetMainMenu(string mUserName)
        {
            var mUserNameParameter = mUserName != null ?
                new ObjectParameter("mUserName", mUserName) :
                new ObjectParameter("mUserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetMainMenu_Result>("proc_GetMainMenu", mUserNameParameter);
        }
    
        public virtual ObjectResult<proc_GetSubMenu_Result> proc_GetSubMenu(string mUserName, string mMenu, string mDate)
        {
            var mUserNameParameter = mUserName != null ?
                new ObjectParameter("mUserName", mUserName) :
                new ObjectParameter("mUserName", typeof(string));
    
            var mMenuParameter = mMenu != null ?
                new ObjectParameter("mMenu", mMenu) :
                new ObjectParameter("mMenu", typeof(string));
    
            var mDateParameter = mDate != null ?
                new ObjectParameter("mDate", mDate) :
                new ObjectParameter("mDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetSubMenu_Result>("proc_GetSubMenu", mUserNameParameter, mMenuParameter, mDateParameter);
        }
    
        public virtual ObjectResult<proc_GetSubMenu2_Result> proc_GetSubMenu2(string mUserName, string mMenu)
        {
            var mUserNameParameter = mUserName != null ?
                new ObjectParameter("mUserName", mUserName) :
                new ObjectParameter("mUserName", typeof(string));
    
            var mMenuParameter = mMenu != null ?
                new ObjectParameter("mMenu", mMenu) :
                new ObjectParameter("mMenu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetSubMenu2_Result>("proc_GetSubMenu2", mUserNameParameter, mMenuParameter);
        }
    
        public virtual ObjectResult<proc_GetUser3_Result> proc_GetUser3(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetUser3_Result>("proc_GetUser3", userNameParameter);
        }
    
        public virtual ObjectResult<proc_GetInstitutionMissingData_Result> proc_GetInstitutionMissingData(string inst)
        {
            var instParameter = inst != null ?
                new ObjectParameter("Inst", inst) :
                new ObjectParameter("Inst", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetInstitutionMissingData_Result>("proc_GetInstitutionMissingData", instParameter);
        }
    
        public virtual ObjectResult<proc_GetMyCapitation_Result> proc_GetMyCapitation(string mInst)
        {
            var mInstParameter = mInst != null ?
                new ObjectParameter("mInst", mInst) :
                new ObjectParameter("mInst", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetMyCapitation_Result>("proc_GetMyCapitation", mInstParameter);
        }
    
        public virtual ObjectResult<proc_Get_Summary_PerInstitutions_Per_Class_By_Gendermvc2_Result> proc_Get_Summary_PerInstitutions_Per_Class_By_Gendermvc2(string mInst)
        {
            var mInstParameter = mInst != null ?
                new ObjectParameter("mInst", mInst) :
                new ObjectParameter("mInst", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_Summary_PerInstitutions_Per_Class_By_Gendermvc2_Result>("proc_Get_Summary_PerInstitutions_Per_Class_By_Gendermvc2", mInstParameter);
        }
    
        public virtual ObjectResult<proc_Get_Summary_PerInstitutionsStaff_By_Gender_Result> proc_Get_Summary_PerInstitutionsStaff_By_Gender(string mInst)
        {
            var mInstParameter = mInst != null ?
                new ObjectParameter("mInst", mInst) :
                new ObjectParameter("mInst", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_Summary_PerInstitutionsStaff_By_Gender_Result>("proc_Get_Summary_PerInstitutionsStaff_By_Gender", mInstParameter);
        }
    
        public virtual ObjectResult<proc_Get_Summary_Staff_Per_Level_Result> proc_Get_Summary_Staff_Per_Level(string mUser)
        {
            var mUserParameter = mUser != null ?
                new ObjectParameter("mUser", mUser) :
                new ObjectParameter("mUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_Summary_Staff_Per_Level_Result>("proc_Get_Summary_Staff_Per_Level", mUserParameter);
        }
    
        public virtual ObjectResult<proc_Get_Summary_Institutions_Per_Level_Result> proc_Get_Summary_Institutions_Per_Level(string mUser)
        {
            var mUserParameter = mUser != null ?
                new ObjectParameter("mUser", mUser) :
                new ObjectParameter("mUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_Summary_Institutions_Per_Level_Result>("proc_Get_Summary_Institutions_Per_Level", mUserParameter);
        }
    
        public virtual ObjectResult<proc_Get_LearnersPerInstitution_Result> proc_Get_LearnersPerInstitution(string mInst, string mGrade)
        {
            var mInstParameter = mInst != null ?
                new ObjectParameter("mInst", mInst) :
                new ObjectParameter("mInst", typeof(string));
    
            var mGradeParameter = mGrade != null ?
                new ObjectParameter("mGrade", mGrade) :
                new ObjectParameter("mGrade", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_LearnersPerInstitution_Result>("proc_Get_LearnersPerInstitution", mInstParameter, mGradeParameter);
        }
    
        public virtual ObjectResult<proc_Get_LearnerTmpPerInstitution_Result> proc_Get_LearnerTmpPerInstitution(string mInst, string mGrade)
        {
            var mInstParameter = mInst != null ?
                new ObjectParameter("mInst", mInst) :
                new ObjectParameter("mInst", typeof(string));
    
            var mGradeParameter = mGrade != null ?
                new ObjectParameter("mGrade", mGrade) :
                new ObjectParameter("mGrade", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_LearnerTmpPerInstitution_Result>("proc_Get_LearnerTmpPerInstitution", mInstParameter, mGradeParameter);
        }
    
        public virtual ObjectResult<proc_Get_InstTypes_Result> proc_Get_InstTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_InstTypes_Result>("proc_Get_InstTypes");
        }
    
        public virtual ObjectResult<proc_Get_InstTypes3_Result> proc_Get_InstTypes3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_InstTypes3_Result>("proc_Get_InstTypes3");
        }
    
        public virtual ObjectResult<proc_Get_ClassGrades2_Result> proc_Get_ClassGrades2(string mInst, string mLevel)
        {
            var mInstParameter = mInst != null ?
                new ObjectParameter("mInst", mInst) :
                new ObjectParameter("mInst", typeof(string));
    
            var mLevelParameter = mLevel != null ?
                new ObjectParameter("mLevel", mLevel) :
                new ObjectParameter("mLevel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_ClassGrades2_Result>("proc_Get_ClassGrades2", mInstParameter, mLevelParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> proc_Get_PageRecords()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("proc_Get_PageRecords");
        }
    
        public virtual ObjectResult<proc_GetLearnerCategory_Result1> proc_GetLearnerCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetLearnerCategory_Result1>("proc_GetLearnerCategory");
        }
    
        public virtual ObjectResult<proc_Get_Learner_Result> proc_Get_Learner(string mUPI)
        {
            var mUPIParameter = mUPI != null ?
                new ObjectParameter("mUPI", mUPI) :
                new ObjectParameter("mUPI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_Learner_Result>("proc_Get_Learner", mUPIParameter);
        }
    
        public virtual ObjectResult<proc_Get_LearnerRecord3_Result> proc_Get_LearnerRecord3(string mUPI, string mBCert)
        {
            var mUPIParameter = mUPI != null ?
                new ObjectParameter("mUPI", mUPI) :
                new ObjectParameter("mUPI", typeof(string));
    
            var mBCertParameter = mBCert != null ?
                new ObjectParameter("mBCert", mBCert) :
                new ObjectParameter("mBCert", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_LearnerRecord3_Result>("proc_Get_LearnerRecord3", mUPIParameter, mBCertParameter);
        }
    
        public virtual ObjectResult<proc_Get_ClassGrades_Result> proc_Get_ClassGrades(string mLevel)
        {
            var mLevelParameter = mLevel != null ?
                new ObjectParameter("mLevel", mLevel) :
                new ObjectParameter("mLevel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_ClassGrades_Result>("proc_Get_ClassGrades", mLevelParameter);
        }
    
        public virtual int proc_InsLearnerWithIndex(string uIC, string uPI, string surname, string otherNames, string firstName, string birth_Cert_No, string dOB, string gender, string nationality, string entry_AS, string class_Code, string disability, string medicalNeed, string mPhone, string mEmail, string mPBox, string mFName, string mMName, string mGName, string mFIDNo, string mMIDNo, string mGIDNo, string mFContacts, string mMContacts, string mGContacts, string mFEmail, string mMEmail, string mGEmail, string mCounty, string mSCounty, string mUserName, string mIndex, ObjectParameter mGenUPI)
        {
            var uICParameter = uIC != null ?
                new ObjectParameter("UIC", uIC) :
                new ObjectParameter("UIC", typeof(string));
    
            var uPIParameter = uPI != null ?
                new ObjectParameter("UPI", uPI) :
                new ObjectParameter("UPI", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("Surname", surname) :
                new ObjectParameter("Surname", typeof(string));
    
            var otherNamesParameter = otherNames != null ?
                new ObjectParameter("OtherNames", otherNames) :
                new ObjectParameter("OtherNames", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var birth_Cert_NoParameter = birth_Cert_No != null ?
                new ObjectParameter("Birth_Cert_No", birth_Cert_No) :
                new ObjectParameter("Birth_Cert_No", typeof(string));
    
            var dOBParameter = dOB != null ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var nationalityParameter = nationality != null ?
                new ObjectParameter("Nationality", nationality) :
                new ObjectParameter("Nationality", typeof(string));
    
            var entry_ASParameter = entry_AS != null ?
                new ObjectParameter("Entry_AS", entry_AS) :
                new ObjectParameter("Entry_AS", typeof(string));
    
            var class_CodeParameter = class_Code != null ?
                new ObjectParameter("Class_Code", class_Code) :
                new ObjectParameter("Class_Code", typeof(string));
    
            var disabilityParameter = disability != null ?
                new ObjectParameter("Disability", disability) :
                new ObjectParameter("Disability", typeof(string));
    
            var medicalNeedParameter = medicalNeed != null ?
                new ObjectParameter("MedicalNeed", medicalNeed) :
                new ObjectParameter("MedicalNeed", typeof(string));
    
            var mPhoneParameter = mPhone != null ?
                new ObjectParameter("mPhone", mPhone) :
                new ObjectParameter("mPhone", typeof(string));
    
            var mEmailParameter = mEmail != null ?
                new ObjectParameter("mEmail", mEmail) :
                new ObjectParameter("mEmail", typeof(string));
    
            var mPBoxParameter = mPBox != null ?
                new ObjectParameter("mPBox", mPBox) :
                new ObjectParameter("mPBox", typeof(string));
    
            var mFNameParameter = mFName != null ?
                new ObjectParameter("mFName", mFName) :
                new ObjectParameter("mFName", typeof(string));
    
            var mMNameParameter = mMName != null ?
                new ObjectParameter("mMName", mMName) :
                new ObjectParameter("mMName", typeof(string));
    
            var mGNameParameter = mGName != null ?
                new ObjectParameter("mGName", mGName) :
                new ObjectParameter("mGName", typeof(string));
    
            var mFIDNoParameter = mFIDNo != null ?
                new ObjectParameter("mFIDNo", mFIDNo) :
                new ObjectParameter("mFIDNo", typeof(string));
    
            var mMIDNoParameter = mMIDNo != null ?
                new ObjectParameter("mMIDNo", mMIDNo) :
                new ObjectParameter("mMIDNo", typeof(string));
    
            var mGIDNoParameter = mGIDNo != null ?
                new ObjectParameter("mGIDNo", mGIDNo) :
                new ObjectParameter("mGIDNo", typeof(string));
    
            var mFContactsParameter = mFContacts != null ?
                new ObjectParameter("mFContacts", mFContacts) :
                new ObjectParameter("mFContacts", typeof(string));
    
            var mMContactsParameter = mMContacts != null ?
                new ObjectParameter("mMContacts", mMContacts) :
                new ObjectParameter("mMContacts", typeof(string));
    
            var mGContactsParameter = mGContacts != null ?
                new ObjectParameter("mGContacts", mGContacts) :
                new ObjectParameter("mGContacts", typeof(string));
    
            var mFEmailParameter = mFEmail != null ?
                new ObjectParameter("mFEmail", mFEmail) :
                new ObjectParameter("mFEmail", typeof(string));
    
            var mMEmailParameter = mMEmail != null ?
                new ObjectParameter("mMEmail", mMEmail) :
                new ObjectParameter("mMEmail", typeof(string));
    
            var mGEmailParameter = mGEmail != null ?
                new ObjectParameter("mGEmail", mGEmail) :
                new ObjectParameter("mGEmail", typeof(string));
    
            var mCountyParameter = mCounty != null ?
                new ObjectParameter("mCounty", mCounty) :
                new ObjectParameter("mCounty", typeof(string));
    
            var mSCountyParameter = mSCounty != null ?
                new ObjectParameter("mSCounty", mSCounty) :
                new ObjectParameter("mSCounty", typeof(string));
    
            var mUserNameParameter = mUserName != null ?
                new ObjectParameter("mUserName", mUserName) :
                new ObjectParameter("mUserName", typeof(string));
    
            var mIndexParameter = mIndex != null ?
                new ObjectParameter("mIndex", mIndex) :
                new ObjectParameter("mIndex", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_InsLearnerWithIndex", uICParameter, uPIParameter, surnameParameter, otherNamesParameter, firstNameParameter, birth_Cert_NoParameter, dOBParameter, genderParameter, nationalityParameter, entry_ASParameter, class_CodeParameter, disabilityParameter, medicalNeedParameter, mPhoneParameter, mEmailParameter, mPBoxParameter, mFNameParameter, mMNameParameter, mGNameParameter, mFIDNoParameter, mMIDNoParameter, mGIDNoParameter, mFContactsParameter, mMContactsParameter, mGContactsParameter, mFEmailParameter, mMEmailParameter, mGEmailParameter, mCountyParameter, mSCountyParameter, mUserNameParameter, mIndexParameter, mGenUPI);
        }
    
        public virtual ObjectResult<proc_InsLearnerWithIndexNew_Result> proc_InsLearnerWithIndexNew(string uIC, string uPI, string surname, string otherNames, string firstName, string birth_Cert_No, string dOB, string gender, string nationality, string entry_AS, string class_Code, string disability, string medicalNeed, string mPhone, string mEmail, string mPBox, string mFName, string mMName, string mGName, string mFIDNo, string mMIDNo, string mGIDNo, string mFContacts, string mMContacts, string mGContacts, string mFEmail, string mMEmail, string mGEmail, string mCounty, string mSCounty, string mUserName, string mIndex)
        {
            var uICParameter = uIC != null ?
                new ObjectParameter("UIC", uIC) :
                new ObjectParameter("UIC", typeof(string));
    
            var uPIParameter = uPI != null ?
                new ObjectParameter("UPI", uPI) :
                new ObjectParameter("UPI", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("Surname", surname) :
                new ObjectParameter("Surname", typeof(string));
    
            var otherNamesParameter = otherNames != null ?
                new ObjectParameter("OtherNames", otherNames) :
                new ObjectParameter("OtherNames", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var birth_Cert_NoParameter = birth_Cert_No != null ?
                new ObjectParameter("Birth_Cert_No", birth_Cert_No) :
                new ObjectParameter("Birth_Cert_No", typeof(string));
    
            var dOBParameter = dOB != null ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var nationalityParameter = nationality != null ?
                new ObjectParameter("Nationality", nationality) :
                new ObjectParameter("Nationality", typeof(string));
    
            var entry_ASParameter = entry_AS != null ?
                new ObjectParameter("Entry_AS", entry_AS) :
                new ObjectParameter("Entry_AS", typeof(string));
    
            var class_CodeParameter = class_Code != null ?
                new ObjectParameter("Class_Code", class_Code) :
                new ObjectParameter("Class_Code", typeof(string));
    
            var disabilityParameter = disability != null ?
                new ObjectParameter("Disability", disability) :
                new ObjectParameter("Disability", typeof(string));
    
            var medicalNeedParameter = medicalNeed != null ?
                new ObjectParameter("MedicalNeed", medicalNeed) :
                new ObjectParameter("MedicalNeed", typeof(string));
    
            var mPhoneParameter = mPhone != null ?
                new ObjectParameter("mPhone", mPhone) :
                new ObjectParameter("mPhone", typeof(string));
    
            var mEmailParameter = mEmail != null ?
                new ObjectParameter("mEmail", mEmail) :
                new ObjectParameter("mEmail", typeof(string));
    
            var mPBoxParameter = mPBox != null ?
                new ObjectParameter("mPBox", mPBox) :
                new ObjectParameter("mPBox", typeof(string));
    
            var mFNameParameter = mFName != null ?
                new ObjectParameter("mFName", mFName) :
                new ObjectParameter("mFName", typeof(string));
    
            var mMNameParameter = mMName != null ?
                new ObjectParameter("mMName", mMName) :
                new ObjectParameter("mMName", typeof(string));
    
            var mGNameParameter = mGName != null ?
                new ObjectParameter("mGName", mGName) :
                new ObjectParameter("mGName", typeof(string));
    
            var mFIDNoParameter = mFIDNo != null ?
                new ObjectParameter("mFIDNo", mFIDNo) :
                new ObjectParameter("mFIDNo", typeof(string));
    
            var mMIDNoParameter = mMIDNo != null ?
                new ObjectParameter("mMIDNo", mMIDNo) :
                new ObjectParameter("mMIDNo", typeof(string));
    
            var mGIDNoParameter = mGIDNo != null ?
                new ObjectParameter("mGIDNo", mGIDNo) :
                new ObjectParameter("mGIDNo", typeof(string));
    
            var mFContactsParameter = mFContacts != null ?
                new ObjectParameter("mFContacts", mFContacts) :
                new ObjectParameter("mFContacts", typeof(string));
    
            var mMContactsParameter = mMContacts != null ?
                new ObjectParameter("mMContacts", mMContacts) :
                new ObjectParameter("mMContacts", typeof(string));
    
            var mGContactsParameter = mGContacts != null ?
                new ObjectParameter("mGContacts", mGContacts) :
                new ObjectParameter("mGContacts", typeof(string));
    
            var mFEmailParameter = mFEmail != null ?
                new ObjectParameter("mFEmail", mFEmail) :
                new ObjectParameter("mFEmail", typeof(string));
    
            var mMEmailParameter = mMEmail != null ?
                new ObjectParameter("mMEmail", mMEmail) :
                new ObjectParameter("mMEmail", typeof(string));
    
            var mGEmailParameter = mGEmail != null ?
                new ObjectParameter("mGEmail", mGEmail) :
                new ObjectParameter("mGEmail", typeof(string));
    
            var mCountyParameter = mCounty != null ?
                new ObjectParameter("mCounty", mCounty) :
                new ObjectParameter("mCounty", typeof(string));
    
            var mSCountyParameter = mSCounty != null ?
                new ObjectParameter("mSCounty", mSCounty) :
                new ObjectParameter("mSCounty", typeof(string));
    
            var mUserNameParameter = mUserName != null ?
                new ObjectParameter("mUserName", mUserName) :
                new ObjectParameter("mUserName", typeof(string));
    
            var mIndexParameter = mIndex != null ?
                new ObjectParameter("mIndex", mIndex) :
                new ObjectParameter("mIndex", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_InsLearnerWithIndexNew_Result>("proc_InsLearnerWithIndexNew", uICParameter, uPIParameter, surnameParameter, otherNamesParameter, firstNameParameter, birth_Cert_NoParameter, dOBParameter, genderParameter, nationalityParameter, entry_ASParameter, class_CodeParameter, disabilityParameter, medicalNeedParameter, mPhoneParameter, mEmailParameter, mPBoxParameter, mFNameParameter, mMNameParameter, mGNameParameter, mFIDNoParameter, mMIDNoParameter, mGIDNoParameter, mFContactsParameter, mMContactsParameter, mGContactsParameter, mFEmailParameter, mMEmailParameter, mGEmailParameter, mCountyParameter, mSCountyParameter, mUserNameParameter, mIndexParameter);
        }
    
        public virtual int proc_DeleteLearner(string uPI, string captured_By, string institution_Code)
        {
            var uPIParameter = uPI != null ?
                new ObjectParameter("UPI", uPI) :
                new ObjectParameter("UPI", typeof(string));
    
            var captured_ByParameter = captured_By != null ?
                new ObjectParameter("Captured_By", captured_By) :
                new ObjectParameter("Captured_By", typeof(string));
    
            var institution_CodeParameter = institution_Code != null ?
                new ObjectParameter("Institution_Code", institution_Code) :
                new ObjectParameter("Institution_Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DeleteLearner", uPIParameter, captured_ByParameter, institution_CodeParameter);
        }
    }
}
