//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewNHIFData
    {
        public string upi { get; set; }
        public string institution_code { get; set; }
        public string surname { get; set; }
        public string firstname { get; set; }
        public string othernames { get; set; }
        public string dob { get; set; }
        public string birth_cert_no { get; set; }
        public string class_code { get; set; }
        public string nationality_code { get; set; }
        public string gender { get; set; }
        public string phone_number { get; set; }
        public string email_address { get; set; }
        public string postal_address { get; set; }
        public string disability_code { get; set; }
        public string med_conditions { get; set; }
        public string father_name { get; set; }
        public string father_idno { get; set; }
        public string father_contacts { get; set; }
        public string mother_name { get; set; }
        public string mother_idno { get; set; }
        public string mother_contacts { get; set; }
        public string guardian_name { get; set; }
        public string guardian_idno { get; set; }
        public string guardian_contacts { get; set; }
        public string father_email { get; set; }
        public string mother_email { get; set; }
        public string guardian_email { get; set; }
        public string status { get; set; }
        public string county_code { get; set; }
        public string sub_county_code { get; set; }
        public string nhif_mem_no { get; set; }
        public string nhif_valid_from { get; set; }
        public string nhif_valid_to { get; set; }
    }
}
