//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhif_student_treatment
    {
        public string Service { get; set; }
        public string VisitID { get; set; }
        public string UPI { get; set; }
        public string hosp_code { get; set; }
        public string hosp_name { get; set; }
        public string Disease_Condition { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> Visit_Date { get; set; }
        public string hosp_country_code { get; set; }
        public string hosp_country_name { get; set; }
        public string hosp_county_code { get; set; }
        public string hosp_county_name { get; set; }
    }
}
