//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhif_student_data
    {
        public string ID { get; set; }
        public string UPI { get; set; }
        public string OtherName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
        public Nullable<System.DateTime> Timestamped { get; set; }
        public string Remark { get; set; }
        public int RunID { get; set; }
    }
}
