//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONS_DUPLICATION_FEB2019
    {
        public int ID { get; set; }
        public string UPI { get; set; }
        public string Birth_Cert_No { get; set; }
        public string ID_No { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string OtherNames { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public string Entry_AS { get; set; }
        public string Entered_By { get; set; }
        public string Date_Entered { get; set; }
        public string UIC { get; set; }
        public string Status { get; set; }
        public string DEL { get; set; }
    }
}
