//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_EXPENDITURE
    {
        public string Unique_Project_Code { get; set; }
        public string Year { get; set; }
        public Nullable<decimal> Estimated_Cost { get; set; }
        public string Source_Code { get; set; }
        public Nullable<decimal> Amount_Disbursed { get; set; }
        public Nullable<decimal> Percentage_Completed { get; set; }
        public Nullable<System.DateTime> Expected_Comp_Date { get; set; }
        public string Status_Code { get; set; }
        public string Done_By { get; set; }
        public Nullable<System.DateTime> Date_Done { get; set; }
        public int Transaction_Id { get; set; }
        public Nullable<decimal> Amount_Spent { get; set; }
    }
}
