//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPApprovalCycle
    {
        public int TransactionID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string FileCode { get; set; }
        public string FileExt { get; set; }
        public string FileContentType { get; set; }
        public string FileName { get; set; }
        public string CategoryID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ProcurementMethod { get; set; }
        public Nullable<System.DateTime> AdvertDate { get; set; }
        public Nullable<System.DateTime> AwardDate { get; set; }
        public string DataImport { get; set; }
        public string ProcessData { get; set; }
        public Nullable<System.DateTime> ProcessDataDate { get; set; }
        public string ProcessDataBy { get; set; }
        public string FileDescription { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovedCaptureBy { get; set; }
        public Nullable<System.DateTime> ApprovedCapturedOn { get; set; }
        public string Published { get; set; }
        public string PublishedBy { get; set; }
        public Nullable<System.DateTime> PublishedOn { get; set; }
        public string Closed { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<System.DateTime> ClosedOn { get; set; }
    }
}
