//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPCashOtherDescription
    {
        public int EntityID { get; set; }
        public string EntityDescription { get; set; }
        public string Bank_code { get; set; }
        public string Branch_code { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string AccessLevel { get; set; }
    }
}
