//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPCashCashOtherFunding_Detailed
    {
        public int TransactionID { get; set; }
        public int EntityID { get; set; }
        public string EntityDescription { get; set; }
        public int CategoryID { get; set; }
        public string FundType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AccountType { get; set; }
        public string AccessLevel { get; set; }
        public string Code { get; set; }
        public string SMPOverhead { get; set; }
        public Nullable<int> Schools { get; set; }
        public Nullable<int> Enrol { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
