//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPFoodItemsPurchaseOrder
    {
        public int TransactionID { get; set; }
        public string FoodID { get; set; }
        public int SupplierID { get; set; }
        public string PONumber { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
    }
}
