//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPFoodPackageGradeLookup
    {
        public int TransactionID { get; set; }
        public string FoodID { get; set; }
        public string GradeID { get; set; }
        public string GradeDescription { get; set; }
        public string Package { get; set; }
        public Nullable<int> PackageWeight { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
    }
}
