//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPFoodItemsSupplied
    {
        public int TransactionID { get; set; }
        public string FoodID { get; set; }
        public int SupplierID { get; set; }
        public string PONumber { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string DeliveryNo { get; set; }
        public Nullable<int> DeliveredQuantity { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> InspectedAcceptedQuantity { get; set; }
        public Nullable<int> InspectedRejectedQuantity { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public string InspectionRemarks { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentVoucherNo { get; set; }
        public Nullable<System.DateTime> S12Date { get; set; }
        public string S12Number { get; set; }
    }
}
