//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPFoodItemsDeleted
    {
        public int TransactionID { get; set; }
        public string FoodID { get; set; }
        public int TermID { get; set; }
        public Nullable<int> FeedingDays { get; set; }
        public Nullable<int> PlannedQuantity { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime DeletedOn { get; set; }
        public string DeletedBy { get; set; }
    }
}
