//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPSchoolsFoodItem
    {
        public int TransactionID { get; set; }
        public string UIC { get; set; }
        public string FoodID { get; set; }
        public int TermID { get; set; }
        public int ExpectedQuantity { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> ActualQuantityDelivered { get; set; }
        public Nullable<System.DateTime> ActualModifiedOn { get; set; }
        public string ActualModifiedBy { get; set; }
        public Nullable<int> RecievedQuantity { get; set; }
        public Nullable<System.DateTime> RecievedOn { get; set; }
        public string RecievedBy { get; set; }
        public Nullable<int> ActualQuantityGramsDelivered { get; set; }
        public Nullable<decimal> ExpectedQuantityKgs { get; set; }
    }
}
