//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPSchoolEnrolment
    {
        public int TransactionID { get; set; }
        public string UIC { get; set; }
        public Nullable<int> Boys { get; set; }
        public Nullable<int> Girls { get; set; }
        public Nullable<int> Unknown { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string SubCtyRouteID { get; set; }
        public Nullable<int> LowerBoys { get; set; }
        public Nullable<int> LowerGirls { get; set; }
        public Nullable<int> LowerUnknown { get; set; }
        public Nullable<int> LowerTotal { get; set; }
    }
}
