//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPSubCountyWarehous
    {
        public int TransactionID { get; set; }
        public string Sub_County_Code { get; set; }
        public string DestinationWarehouse { get; set; }
        public string Consignee { get; set; }
        public string PhysicalAddress { get; set; }
    }
}
