//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPSchoolDailyAttendanceComplete
    {
        public string UICAttendance { get; set; }
        public Nullable<int> TotalAttendance { get; set; }
        public Nullable<int> TotalLowerGradeAttendance { get; set; }
        public string Processed { get; set; }
        public Nullable<System.DateTime> ProcessedOn { get; set; }
    }
}
