//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPSchoolRecieveProcuredFoodItemsForCash
    {
        public int TransactionID { get; set; }
        public string UIC { get; set; }
        public int TermID { get; set; }
        public string FoodID { get; set; }
        public int DeliveryNoteID { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> DeliveredQuantity { get; set; }
        public string RecievedBy { get; set; }
        public Nullable<System.DateTime> ReceivedOn { get; set; }
        public string PostStore { get; set; }
        public string PostStoreBy { get; set; }
        public Nullable<System.DateTime> PostStoreOn { get; set; }
    }
}
