//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPSchoolsDeliveryNotesFoodItem
    {
        public int TransactionID { get; set; }
        public string UIC { get; set; }
        public string FoodID { get; set; }
        public int TermID { get; set; }
        public string DeliveryNoteNo { get; set; }
        public Nullable<int> DispatchedQuantity { get; set; }
        public Nullable<int> RecievedQuantity { get; set; }
        public Nullable<int> RecievedQuantityKGs { get; set; }
        public Nullable<int> RecievedQuantityGrams { get; set; }
        public Nullable<System.DateTime> RecievedOn { get; set; }
        public string RecievedBy { get; set; }
        public string RecievedRemark { get; set; }
        public string DispatchedBy { get; set; }
        public Nullable<System.DateTime> DispatchedOn { get; set; }
        public Nullable<int> RejectedQuantity { get; set; }
        public string DeliveryNoteCloseFlag { get; set; }
        public string DeliveryNoteClosedBy { get; set; }
        public Nullable<System.DateTime> DeliveryNoteClosedDate { get; set; }
        public Nullable<int> DispatchedQuantityGrams { get; set; }
    }
}
