//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPSchoolProcurementPlanForCash
    {
        public int TransactionID { get; set; }
        public string UIC { get; set; }
        public string FoodID { get; set; }
        public int TermID { get; set; }
        public Nullable<int> PlannedQuantity { get; set; }
        public Nullable<decimal> EstimatedPrice { get; set; }
        public string SupplierName { get; set; }
        public string SupplierContact { get; set; }
        public Nullable<System.DateTime> AwardDate { get; set; }
        public Nullable<decimal> ActualPrice { get; set; }
        public Nullable<int> ActualQuantity { get; set; }
        public string LPO { get; set; }
    }
}
