//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPSchoolDailyFoodRelease
    {
        public string UICAttendanceID { get; set; }
        public int FoodID { get; set; }
        public Nullable<int> TotalAttendance { get; set; }
        public Nullable<int> TotalLowerGradeAttendance { get; set; }
        public Nullable<int> PlannedDailyQuantityGrams { get; set; }
        public Nullable<int> PlannedDailyQuantityKGs { get; set; }
        public Nullable<int> QuantityGrams { get; set; }
        public Nullable<int> QuantityKGs { get; set; }
        public Nullable<System.DateTime> ReleasedOn { get; set; }
        public string ReleasedBy { get; set; }
        public string UpdateStore { get; set; }
        public string Remark { get; set; }
    }
}
