//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPSchools_Final_Disbursement
    {
        public int TransactionID { get; set; }
        public string UIC { get; set; }
        public int TermID { get; set; }
        public string Institution_Name { get; set; }
        public Nullable<int> FeedingDays { get; set; }
        public Nullable<int> Enrol { get; set; }
        public string AccType { get; set; }
        public string Bank_Name { get; set; }
        public string Sort_Code { get; set; }
        public string Branch_Name { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<bool> AcknowledgeReceipt { get; set; }
        public string FileCode { get; set; }
        public string FileExt { get; set; }
        public string FileContentType { get; set; }
        public string FileName { get; set; }
        public Nullable<decimal> UsedAmount { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
        public string ReceiptRemarks { get; set; }
        public Nullable<decimal> RecieptAmount { get; set; }
    }
}
