//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPSchoolStoreForCash
    {
        public string UIC { get; set; }
        public string FoodID { get; set; }
        public Nullable<double> InitialQuantity { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> InitialQuantityGrams { get; set; }
        public Nullable<int> QuantityGrams { get; set; }
        public string CapturedBy { get; set; }
        public Nullable<System.DateTime> CapturedOn { get; set; }
        public string Modifiedby { get; set; }
    }
}
