//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPTransporterLookup
    {
        public int TransactionID { get; set; }
        public int TransporterID { get; set; }
        public string Name { get; set; }
        public string Contacts { get; set; }
        public Nullable<int> AllocatedTonage { get; set; }
        public Nullable<int> NoTrucks { get; set; }
        public string DEL { get; set; }
    }
}
