//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPWayBillDetail
    {
        public int WayBillNo { get; set; }
        public int SupplierID { get; set; }
        public string FoodID { get; set; }
        public Nullable<int> QuantityDispatched { get; set; }
        public Nullable<int> QuantityRecieved { get; set; }
        public Nullable<System.DateTime> DateRecieved { get; set; }
        public string RecievedBy { get; set; }
        public Nullable<int> QuantityRejected { get; set; }
        public string RecievedRemark { get; set; }
        public string FoodItemCapturedBy { get; set; }
        public Nullable<System.DateTime> FoodItemCapturedOn { get; set; }
        public string DispatchedWeight { get; set; }
        public string CompositeKey { get; set; }
    }
}
