//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPWaybillBasic
    {
        public int WayBillNo { get; set; }
        public string Sub_County_Code { get; set; }
        public string DestinationWarehouse { get; set; }
        public Nullable<System.DateTime> LoadingDate { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public string DispatchRemarks { get; set; }
        public Nullable<int> TransporterID { get; set; }
        public string VehicleRegNo { get; set; }
        public string FinalVehicleRegNo { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public string WayBillNoCloseFlag { get; set; }
        public string WayBillNoCloseFlagBy { get; set; }
        public Nullable<System.DateTime> WayBillNoCloseFlagDate { get; set; }
        public string SubCountyReceiveFlag { get; set; }
    }
}
