//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_DESIGNATIONS
    {
        public string Designation_code { get; set; }
        public string Designation_Name { get; set; }
        public string Job_Group { get; set; }
        public string Category { get; set; }
    }
}
