//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_QUALIFICATIONS
    {
        public string UPI { get; set; }
        public string Programme_Code { get; set; }
        public string Training_Institution_Code { get; set; }
        public string Training_Mode { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Award_Code { get; set; }
        public string Done_by { get; set; }
        public Nullable<System.DateTime> Date_done { get; set; }
        public int Idx { get; set; }
    }
}
