//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_parameters
    {
        public string parameter_code { get; set; }
        public string Parameter_name { get; set; }
        public string Parameter_value { get; set; }
        public string Parameter_description { get; set; }
    }
}
