//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEMLOG
    {
        public int ApplicationID { get; set; }
        public int LogID { get; set; }
        public string LogSubject { get; set; }
        public string MessageLog { get; set; }
        public Nullable<bool> Successful { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UserCategory { get; set; }
    }
}
