//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TALENT
    {
        public int Transaction_ID { get; set; }
        public string UPI { get; set; }
        public string Talent_Code { get; set; }
        public string Talent_Details { get; set; }
        public string Academic_Year { get; set; }
        public string Institution_Code { get; set; }
        public string Captured_By { get; set; }
        public Nullable<System.DateTime> Date_Captured { get; set; }
    }
}
