//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHERS_RESPONSIBILITY
    {
        public int ID { get; set; }
        public string UPI { get; set; }
        public string Institution_Code { get; set; }
        public string Responsibility_Code { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<System.DateTime> Date_Captured { get; set; }
        public string Captured_by { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
