//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_INSTITUTIONS
    {
        public string Training_Institution_Code { get; set; }
        public string Training_Institution_Name { get; set; }
        public int Idx { get; set; }
    }
}
