//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userid { get; set; }
        public string Institution_Code { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Surname { get; set; }
        public string Other_Name { get; set; }
        public string Status { get; set; }
        public string Role_ID { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string Created_By { get; set; }
        public string Creator_Title { get; set; }
        public string IDNO { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public string SMSCode { get; set; }
        public string SMSCodeStatus { get; set; }
        public string DateSent { get; set; }
        public string Captured_By { get; set; }
        public string Gender { get; set; }
        public string JobTitle { get; set; }
        public string Responsibilities { get; set; }
        public string Grpuserid { get; set; }
        public string NewPass { get; set; }
    }
}
