//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERCATEGORY
    {
        public int UID { get; set; }
        public string Dep { get; set; }
        public string Description { get; set; }
        public Nullable<int> Locks { get; set; }
    }
}
