//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAdmission
    {
        public int IDx { get; set; }
        public string INDEX_NO { get; set; }
        public string GE { get; set; }
        public string NAME { get; set; }
        public string School_Name { get; set; }
        public string TOT { get; set; }
        public string district_code { get; set; }
        public string district_name { get; set; }
        public string YOB { get; set; }
        public string School_Category { get; set; }
        public string Selected_School { get; set; }
        public string Method { get; set; }
        public string SchoolAdmitted { get; set; }
        public string Category2 { get; set; }
        public string PlacementHistory { get; set; }
    }
}
