//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLearnerScholarship
    {
        public string Institution_Name { get; set; }
        public string County_Name { get; set; }
        public string Sub_County_Name { get; set; }
        public string UPI { get; set; }
        public string FullName { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string OtherNames { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string Birth_Cert_No { get; set; }
        public string Level_Name { get; set; }
        public string Institution_Type { get; set; }
        public string Class_Name { get; set; }
    }
}
