//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLearner
    {
        public string Institution_Code { get; set; }
        public string Institution_Name { get; set; }
        public string County_Name { get; set; }
        public string County_Code { get; set; }
        public string Sub_County_Name { get; set; }
        public string Sub_County_Code { get; set; }
        public string Institution_Level_Code { get; set; }
        public string Institution_Type { get; set; }
        public string UPI { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string OtherNames { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string Birth_Cert_No { get; set; }
        public string Country_Name { get; set; }
        public string Class_Name { get; set; }
        public string Special_Medical_Condition { get; set; }
        public string Father_Name { get; set; }
        public string Father_IDNo { get; set; }
        public string Father_Contacts { get; set; }
        public string Father_Email { get; set; }
        public string Mother_Name { get; set; }
        public string Mother_IDNo { get; set; }
        public string Mother_Contacts { get; set; }
        public string Mother_Email { get; set; }
        public string Date_Captured { get; set; }
        public string Guardian_Name { get; set; }
        public string Guardian_IDNo { get; set; }
        public string Guardian_Contacts { get; set; }
        public string Guardian_Email { get; set; }
        public Nullable<int> Status { get; set; }
        public string Photo { get; set; }
    }
}
